<a href="https://colab.research.google.com/github/Gitanjali1992/pandas/blob/main/Working_WIth_Data_Frames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# pip install pandas --upgrade
pd.__version__

'1.3.5'

# What is a DataFrame?

In [ ]:
# some python lists
names = ['Olga', 'Andrew', 'Brian', 'Telulah', 'Nicole', 'Tilda']
ages = [29, 21, 45, 23, 39, 46]
married = [False, True, True, True, False, True]

In [ ]:
# pandas series
ser = pd.Series(names, name='name')

In [ ]:
# pandas dataframe
df = pd.DataFrame({'name': names, 'age': ages, 'married': married})

In [ ]:
ser

0       Olga
1     Andrew
2      Brian
3    Telulah
4     Nicole
5      Tilda
Name: name, dtype: object

In [ ]:
df

      name  age  married
0     Olga   29    False
1   Andrew   21     True
2    Brian   45     True
3  Telulah   23     True
4   Nicole   39    False
5    Tilda   46     True

In [ ]:
ser.iloc[2]

'Brian'

In [ ]:
df.iloc[2,0]

'Brian'

In [ ]:
df.iloc[2]

name       Brian
age           45
married     True
Name: 2, dtype: object

In [ ]:
ser.ndim

1

In [ ]:
df.ndim

2

In [ ]:
ser.shape

(6,)

In [ ]:
df.shape

(6, 3)

In [ ]:
ser

0       Olga
1     Andrew
2      Brian
3    Telulah
4     Nicole
5      Tilda
Name: name, dtype: object

In [ ]:
df.name

0       Olga
1     Andrew
2      Brian
3    Telulah
4     Nicole
5      Tilda
Name: name, dtype: object

In [ ]:
# df.dtype

In [ ]:
df.dtypes

name       object
age         int64
married      bool
dtype: object

# Creating A DataFrame

* Column-Based approach --> building column by column
  * dict of lists
  * dict of tuples
  * dict of series
  * dict of dicts
* Row-Based approach --> building row by row
  * list of dicts

Using Python **Dictionary of Lists** where:
* Keys as --> Python Strings
* Values as --> Python Lists
  * Make sure that all passed lists have same length. Else there will be "ValueError"

In [ ]:
# names = ['Olga', 'Andrew', 'Brian', 'Telulah', 'Nicole', 'Tilda']
# ages = [29, 21, 45, 23, 39, 46]
# married = [False, True, True, True, False, True]
pd.DataFrame({'name':names, 'age':ages, 'married':married})

      name  age  married
0     Olga   29    False
1   Andrew   21     True
2    Brian   45     True
3  Telulah   23     True
4   Nicole   39    False
5    Tilda   46     True

In [ ]:
new_names = names + ['Gitanjali']
# ages = [29, 21, 45, 23, 39, 46]
# married = [False, True, True, True, False, True]
# pd.DataFrame({'name':new_names, 'age':ages, 'married':married})

Using Python **Dictionary of Tuples** where:
* Keys as --> Python Strings
* Values as --> Python Tuples

In [ ]:
tuple_names = tuple(names)
tuple_ages = tuple(ages)
tuple_married = tuple(married)

In [ ]:
pd.DataFrame({'name':tuple_names,
              'age':tuple_ages,
              'married':tuple_married})

      name  age  married
0     Olga   29    False
1   Andrew   21     True
2    Brian   45     True
3  Telulah   23     True
4   Nicole   39    False
5    Tilda   46     True

Using Python ***Dictionary of Series*** where:
* Keys as --> Python Strings
* Values as --> Python Series

In [ ]:
series_names = pd.Series(names)
series_ages = pd.Series(ages)
series_married = pd.Series(married)

In [ ]:
pd.DataFrame({'name':series_names,
              'age':series_ages,
              'married':series_married})

      name  age  married
0     Olga   29    False
1   Andrew   21     True
2    Brian   45     True
3  Telulah   23     True
4   Nicole   39    False
5    Tilda   46     True

Using Python **Dictionary of Dictionaries** where:
* Keys as --> Python Strings
* Values as --> Python Series

In [ ]:
list(enumerate(names))

[(0, 'Olga'),
 (1, 'Andrew'),
 (2, 'Brian'),
 (3, 'Telulah'),
 (4, 'Nicole'),
 (5, 'Tilda')]

In [ ]:
# using dictionary comprehensions on enumerate to get dictionary of names, ages and married:
dict_names = {k:v for k,v in enumerate(names)}
dict_names
dict_ages = {k:v for k,v in enumerate(ages)}
dict_ages
dict_married ={k:v for k,v in enumerate(married)}
dict_married

{0: False, 1: True, 2: True, 3: True, 4: False, 5: True}

In [ ]:
pd.DataFrame({'name':dict_names, 'age':dict_ages, 'married':dict_married})

      name  age  married
0     Olga   29    False
1   Andrew   21     True
2    Brian   45     True
3  Telulah   23     True
4   Nicole   39    False
5    Tilda   46     True

In [ ]:
def convert_list_to_dict(input_list):
  return {k:v for k,v in enumerate(input_list)}

dict_names1 = convert_list_to_dict(names)
dict_ages1 = convert_list_to_dict(ages)
dict_married1 = convert_list_to_dict(married)

pd.DataFrame({'name':dict_names1, 'age':dict_ages1, 'married':dict_married1})

      name  age  married
0     Olga   29    False
1   Andrew   21     True
2    Brian   45     True
3  Telulah   23     True
4   Nicole   39    False
5    Tilda   46     True

Using Python List of Dictionaries
* Row-Centric approach to build DataFrame

In [ ]:
list(zip(names, ages, married))

[('Olga', 29, False),
 ('Andrew', 21, True),
 ('Brian', 45, True),
 ('Telulah', 23, True),
 ('Nicole', 39, False),
 ('Tilda', 46, True)]

In [ ]:
for name, age, married in zip(names, ages, married):
  print(name, age, married)

Olga 29 False
Andrew 21 True
Brian 45 True
Telulah 23 True
Nicole 39 False
Tilda 46 True

In [ ]:
rowwise = [{'name':name, 'age':age} for name, age in zip(names, ages)]
# rowwise = [{'name': name, 'age': ages, 'married': married} for name, ages, married in zip(names, ages, married)]

In [ ]:
pd.DataFrame(rowwise)

      name  age
0     Olga   29
1   Andrew   21
2    Brian   45
3  Telulah   23
4   Nicole   39
5    Tilda   46

# The info() Method

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     6 non-null      object
 1   age      6 non-null      int64
 2   married  6 non-null      bool
dtypes: bool(1), int64(1), object(1)
memory usage: 230.0+ bytes

For larger dataframes with more columns, above output can get overwhelming. To deal with that we have 2 input parameters in .info() method which we can specify.

verbose:
* verbose=False --> no column specifics
* verbose=True --> all column specifics

In [ ]:
df.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Columns: 3 entries, name to married
dtypes: bool(1), int64(1), object(1)
memory usage: 230.0+ bytes

In [ ]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     6 non-null      object
 1   age      6 non-null      int64
 2   married  6 non-null      bool
dtypes: bool(1), int64(1), object(1)
memory usage: 230.0+ bytes

In [ ]:
# df.info() ~ df.info(verbose=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     6 non-null      object
 1   age      6 non-null      int64
 2   married  6 non-null      bool
dtypes: bool(1), int64(1), object(1)
memory usage: 230.0+ bytes

max_cols:
* max_cols < Total_column_count --> no column specifics
* max_cols > Total_column_count --> all column specifics

In [ ]:
df.info(max_cols=2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Columns: 3 entries, name to married
dtypes: bool(1), int64(1), object(1)
memory usage: 230.0+ bytes

In [ ]:
df.info(max_cols=4)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     6 non-null      object
 1   age      6 non-null      int64
 2   married  6 non-null      bool
dtypes: bool(1), int64(1), object(1)
memory usage: 230.0+ bytes

In [ ]:
# df.info(max_cols = grater than total_column_count) ~ df.info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     6 non-null      object
 1   age      6 non-null      int64
 2   married  6 non-null      bool
dtypes: bool(1), int64(1), object(1)
memory usage: 230.0+ bytes

memory_usage
* memory_usage=True --> will display memory usage estimate number in the output
* memory_usage=False --> will not display memory usage estimate number in the output
* memory_usage='deep' --> will display memory usage exact number in the output

In [ ]:
# df.info(memory_usage=True) ~ df.info()
df.info(memory_usage=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     6 non-null      object
 1   age      6 non-null      int64
 2   married  6 non-null      bool
dtypes: bool(1), int64(1), object(1)
memory usage: 230.0+ bytes

In [ ]:
df.info(memory_usage=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     6 non-null      object
 1   age      6 non-null      int64
 2   married  6 non-null      bool
dtypes: bool(1), int64(1), object(1)

In [ ]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     6 non-null      object
 1   age      6 non-null      int64
 2   married  6 non-null      bool
dtypes: bool(1), int64(1), object(1)
memory usage: 557.0 bytes

# Reading In Nutrition Data

In [ ]:
dataurl = 'https://andybek.com/pandas-nutrition'

In [ ]:
nutrition = pd.read_csv(dataurl)

In [ ]:
nutrition.head(n=10)

,Unnamed: 0,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,0,Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
1,1,"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
2,2,"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
3,3,"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
4,4,"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g
5,5,"Cauliflower, raw",100 g,25,0.3g,0.1g,0,30.00 mg,44.3 mg,57.00 mcg,...,0.28 g,0.130 g,0.034 g,0.031 g,0.00 mg,0.0 g,0.76 g,0.00 mg,0.00 mg,92.07 g
6,6,"Taro leaves, raw",100 g,42,0.7g,0.2g,0,3.00 mg,12.8 mg,126.00 mcg,...,0.74 g,0.151 g,0.060 g,0.307 g,0.00 mg,0.0 g,1.92 g,0.00 mg,0.00 mg,85.66 g
7,7,"Lamb, raw, ground",100 g,282,23g,10g,73mg,59.00 mg,69.3 mg,18.00 mcg,...,23.41 g,10.190 g,9.600 g,1.850 g,73.00 mg,0.0 g,0.87 g,0.00 mg,0.00 mg,59.47 g
8,8,"Cheese, camembert",100 g,300,24g,15g,72mg,842.00 mg,15.4 mg,62.00 mcg,...,24.26 g,15.259 g,7.023 g,0.724 g,72.00 mg,0.0 g,3.68 g,0.00 mg,0.00 mg,51.80 g
9,9,Vegetarian fillets,100 g,290,18g,2.8g,0,490.00 mg,82.0 mg,102.00 mcg,...,18.00 g,2.849 g,4.376 g,9.332 g,0.00 mg,0.0 g,5.00 g,0.00 mg,0.00 mg,45.00 g

In [ ]:
nutrition.info(verbose=False, memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8789 entries, 0 to 8788
Columns: 77 entries, Unnamed: 0 to water
dtypes: int64(3), object(74)
memory usage: 39.2 MB

# Some Cleanup: Removing the Duplicate Index

In [ ]:
nutrition.head()

,Unnamed: 0,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,0,Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
1,1,"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
2,2,"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
3,3,"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
4,4,"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

Method 1: Dropping the unwanted column

* .drop(column_name, axis=1)
* uses axis=1 to indicate we are deleting from list of columns
* Does not modify the list in place, Returns a new dataframe

In [ ]:
nutrition.drop('Unnamed: 0', axis=1).head()

,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
1,"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
2,"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
3,"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
4,"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

In [ ]:
nutrition.head()

,Unnamed: 0,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,0,Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
1,1,"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
2,2,"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
3,3,"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
4,4,"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

Method 2: Set the unwantyed column as index
* .set_index(column_name)
* Replaces teh RangeIndex with the passed column as new index
* Not in-place, Returns a new dataframe

In [ ]:
nutrition.set_index('Unnamed: 0').head()

,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
0,Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
1,"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
2,"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
3,"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
4,"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

In [ ]:
nutrition.head()

,Unnamed: 0,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,0,Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
1,1,"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
2,2,"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
3,3,"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
4,4,"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

Method3: While reading teh dataset initially mark that column as Index
* pd.read_csv(dataurl, index_col=[0])
* preferred way as dataset not modified

In [ ]:
nutrition = pd.read_csv(dataurl, index_col=[0])

In [ ]:
nutrition.head()

,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
1,"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
2,"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
3,"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
4,"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

# The sample() Method
* Always returns one random record/observation each time we call it
* .sample(random_state=n) --> Returns same record each time we query it
* .sample(n=record_count) --> Returns record_count random records
* .sample(frac=fraction_value) --> Returns fraction of teh total records
* n and frac parameters can't be used together in single sample() call

In [ ]:
nutrition.sample()

,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
7006,"Lamb, braised, cooked, separable lean and fat,...",100 g,247,14g,5.4g,111mg,69.00 mg,0,0,0,...,14.22 g,5.405 g,4.055 g,0.693 g,111.00 mg,0.0 g,1.00 g,0.00 mg,0.00 mg,56.87 g

In [ ]:
nutrition.sample(random_state=12)

,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
3713,"Thuringer, pork, beef, summer sausage, cervelat",100 g,362,30g,12g,74mg,1300.00 mg,78.9 mg,2.00 mcg,0.00 mcg,...,30.43 g,11.510 g,12.970 g,1.200 g,74.00 mg,0.0 g,3.63 g,0.00 mg,0.00 mg,45.18 g

In [ ]:
nutrition.sample(n=3)
# .sample(n=1) ~ .sample()

,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
458,"Rye flour, dark",100 g,325,2.2g,0.3g,0,2.00 mg,30.4 mg,33.00 mcg,0.00 mcg,...,2.22 g,0.269 g,0.284 g,1.046 g,0.00 mg,0.0 g,2.50 g,0.00 mg,0.00 mg,10.75 g
6318,"Fish, drained solids with bone, without salt, ...",100 g,153,7.3g,1.6g,44mg,75.00 mg,0,10.00 mcg,0.00 mcg,...,7.31 g,1.644 g,2.776 g,2.277 g,44.00 mg,0,2.70 g,0,0,68.72 g
6471,"Pork, roasted, cooked, separable lean only, te...",100 g,143,3.5g,1.2g,73mg,57.00 mg,88.9 mg,0.00 mcg,0.00 mcg,...,3.51 g,1.198 g,1.334 g,0.506 g,73.00 mg,0.0 g,1.21 g,0.00 mg,0.00 mg,69.45 g

In [ ]:
nutrition.sample(frac=0.01)

,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
1860,"BURGER KING, no cheese, WHOPPER",100 g,233,13g,4.3g,30mg,313.00 mg,0,47.00 mcg,33.00 mcg,...,12.84 g,4.250 g,4.685 g,3.389 g,30.00 mg,0,1.43 g,0,0,56.43 g
5402,"Plums, solids and liquids, water pack, purple,...",100 g,41,0g,NaN,0,1.00 mg,1.3 mg,3.00 mcg,0.00 mcg,...,0.01 g,0.001 g,0.005 g,0.002 g,0.00 mg,0.0 g,0.23 g,0.00 mg,0.00 mg,88.35 g
5946,"CAMPBELL'S Red and White, condensed, Cream of ...",100 g,89,5.7g,1.6g,4mg,669.00 mg,0,0,0,...,5.65 g,1.613 g,0.806 g,3.226 g,4.00 mg,0,1.58 g,0,0,83.90 g
3935,"Chicken, roasted, cooked, meat only, roasting",100 g,167,6.6g,1.8g,75mg,75.00 mg,0,5.00 mcg,0.00 mcg,...,6.63 g,1.810 g,2.500 g,1.510 g,75.00 mg,0,0.95 g,0,0,67.41 g
8656,"Lamb, roasted, cooked, choice, trimmed to 1/4""...",100 g,225,12g,5.1g,90mg,65.00 mg,0,22.00 mcg,0.00 mcg,...,12.45 g,5.090 g,5.290 g,0.880 g,90.00 mg,0,1.05 g,0,0,60.66 g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5599,"Infant Formula, powder, Infant, Premium, ENFAM...",100 g,510,27g,11g,0,138.00 mg,121.0 mg,81.00 mcg,81.00 mcg,...,27.00 g,11.161 g,9.987 g,5.213 g,0.00 mg,0.0 g,3.00 g,0.00 mg,0.00 mg,2.40 g
260,"Fish, raw, tilefish",100 g,96,2.3g,0.4g,50mg,53.00 mg,0,15.00 mcg,0.00 mcg,...,2.31 g,0.441 g,0.571 g,0.599 g,50.00 mg,0.0 g,1.14 g,0,0,78.90 g
7971,"Cereals, without salt, microwaved, cooked with...",100 g,55,0.4g,0.1g,0,4.00 mg,0,30.00 mcg,16.00 mcg,...,0.37 g,0.094 g,0.049 g,0.194 g,0,0,0.49 g,0,0,86.51 g
7018,"Bread, and rice flour, rice starch, made with ...",100 g,320,11g,0.3g,0,0,0,0,0,...,10.70 g,0.339 g,7.363 g,2.218 g,0,0,1.68 g,0,0,31.67 g
8163,"Beef, grilled, cooked, all grades, trimmed to ...",100 g,246,16g,5.6g,76mg,86.00 mg,0,6.00 mcg,0.00 mcg,...,15.70 g,5.566 g,6.828 g,0.586 g,76.00 mg,0.0 g,0.94 g,0.00 mg,0.00 mg,57.18 g

# Bonus: Sampling with Replacement or Weights
* Sampling with Replacement --> .sample(replace=True)
  * we can end up getting same exact record multiple times
* Sampling with Weights --> .sample(weights=weigths_series)
  * More the weight , more likely to be picked up

In [ ]:
nutrition.sample(n=3, replace=True)

,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
7618,"Lamb, braised, cooked, choice, trimmed to 1/4""...",100 g,243,13g,5.6g,106mg,72.00 mg,110.0 mg,17.00 mcg,0.00 mcg,...,13.46 g,5.630 g,5.680 g,0.970 g,106.00 mg,0.0 g,0.91 g,0.00 mg,0.00 mg,56.80 g
1068,"Quail, raw, meat and skin",100 g,192,12g,3.4g,76mg,53.00 mg,0,8.00 mcg,0.00 mcg,...,12.05 g,3.380 g,4.180 g,2.980 g,76.00 mg,0.0 g,0.90 g,0,0,69.65 g
4211,"Cereals ready-to-eat, RAISIN NUT BRAN, GENERAL...",100 g,368,5.3g,1g,0,440.00 mg,24.3 mg,204.00 mcg,185.00 mcg,...,5.30 g,1.000 g,2.000 g,2.000 g,0.00 mg,0.0 g,2.59 g,0.00 mg,0.00 mg,4.03 g

In [ ]:
weights = pd.Series(data=[10,10,10,1,2], index=[7,17,29,5,6])
weights

7     10
17    10
29    10
5      1
6      2
dtype: int64

In [ ]:
nutrition.sample(n=3, weights=weights)

,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
7,"Lamb, raw, ground",100 g,282,23g,10g,73mg,59.00 mg,69.3 mg,18.00 mcg,0.00 mcg,...,23.41 g,10.190 g,9.600 g,1.850 g,73.00 mg,0.0 g,0.87 g,0.00 mg,0.00 mg,59.47 g
29,"Nuts, dried, pine nuts",100 g,673,68g,4.9g,0,2.00 mg,55.8 mg,34.00 mcg,0.00 mcg,...,68.37 g,4.899 g,18.764 g,34.071 g,0.00 mg,0.0 g,2.59 g,0.00 mg,0.00 mg,2.28 g
17,"Peppers, raw, jalapeno",100 g,29,0.4g,0.1g,0,3.00 mg,7.5 mg,27.00 mcg,0.00 mcg,...,0.37 g,0.092 g,0.029 g,0.112 g,0.00 mg,0.0 g,0.53 g,0.00 mg,0.00 mg,91.69 g

# DataFrame Axes
* .axes 
* Returns a Python list of 2 Pandas Index objects
  * one characterizing the rows: axes=0
  * one characterizing the columns: axes=1
* axes=0 --> Row Index Labels
* axes=1 --> Column Index Labels

In [ ]:
nutrition.axes

[Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
             ...
             8779, 8780, 8781, 8782, 8783, 8784, 8785, 8786, 8787, 8788],
            dtype='int64', length=8789),
 Index(['name', 'serving_size', 'calories', 'total_fat', 'saturated_fat',
        'cholesterol', 'sodium', 'choline', 'folate', 'folic_acid', 'niacin',
        'pantothenic_acid', 'riboflavin', 'thiamin', 'vitamin_a',
        'vitamin_a_rae', 'carotene_alpha', 'carotene_beta',
        'cryptoxanthin_beta', 'lutein_zeaxanthin', 'lucopene', 'vitamin_b12',
        'vitamin_b6', 'vitamin_c', 'vitamin_d', 'vitamin_e', 'tocopherol_alpha',
        'vitamin_k', 'calcium', 'copper', 'irom', 'magnesium', 'manganese',
        'phosphorous', 'potassium', 'selenium', 'zink', 'protein', 'alanine',
        'arginine', 'aspartic_acid', 'cystine', 'glutamic_acid', 'glycine',
        'histidine', 'hydroxyproline', 'isoleucine', 'leucine', 'lysine',
        'methionine', 'phenylalanine', 'proline', 'serine', 'threonine',
        'tryptophan', 'tyrosine', 'valine', 'carbohydrate', 'fiber', 'sugars',
        'fructose', 'galactose', 'glucose', 'lactose', 'maltose', 'sucrose',
        'fat', 'saturated_fatty_acids', 'monounsaturated_fatty_acids',
        'polyunsaturated_fatty_acids', 'fatty_acids_total_trans', 'alcohol',
        'ash', 'caffeine', 'theobromine', 'water'],
       dtype='object')]

In [ ]:
nutrition.axes[0][3]

3

In [ ]:
nutrition.index[3]

3

In [ ]:
nutrition.axes[1][69]

'polyunsaturated_fatty_acids'

In [ ]:
nutrition.columns[69]

'polyunsaturated_fatty_acids'

# Changing The Index

In [ ]:
nutrition.index

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            8779, 8780, 8781, 8782, 8783, 8784, 8785, 8786, 8787, 8788],
           dtype='int64', length=8789)

In [ ]:
type(nutrition.index)

pandas.core.indexes.numeric.Int64Index

In [ ]:
# Creating RangeIndex in pandas
pd.RangeIndex(start=0, stop=8789, step=1)

RangeIndex(start=0, stop=8789, step=1)

In [ ]:
# Changing the index of our dataframe to RangeIndex
nutrition.index = pd.RangeIndex(start=0, stop=8789, step=1)
type(nutrition.index)

pandas.core.indexes.range.RangeIndex

In [ ]:
nutrition.index

RangeIndex(start=0, stop=8789, step=1)

Setting the index to a specific column from our column list using .set_index()

In [ ]:
nutrition.set_index('name').head()
# Does not modify teh original list
# Returns a copy of the dataframe with the modified index

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,0.000 mg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,1.167 mg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,0.649 mg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,3.363 mg,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,0.063 mg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

In [ ]:
nutrition.head()

,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
1,"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
2,"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
3,"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
4,"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

In [ ]:
# inplace 
# inplace=True --> will modify the dataframe in place
nutrition.set_index('name', inplace=True)

In [ ]:
nutrition.head()

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,0.000 mg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,1.167 mg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,0.649 mg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,3.363 mg,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,0.063 mg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

In [ ]:
# drop
# drop=True --> Removes the column we passed as index from our column list, Default.
# drop=False --> Keeps the column passed as both index and column in column list.
# nutrition.set_index('name', drop=True) ~ nutrition.set_index('name')
nutrition.set_index('folic_acid', drop=False).head()

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
folic_acid,,,,,,,,,,,,,,,,,,,,,
0.00 mcg,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,0.000 mg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
0.00 mcg,100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,1.167 mg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
0.00 mcg,100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,0.649 mg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
0,100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,3.363 mg,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
0.00 mcg,100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,0.063 mg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

In [ ]:
# append
# Gives the option to append a new index to the existing index
# We end up getting a multi-index (index that has many levels)
nutrition.set_index('folic_acid', drop=False, append=True).head()

,,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,folic_acid,,,,,,,,,,,,,,,,,,,,,
Cornstarch,0.00 mcg,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,0.000 mg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
"Nuts, pecans",0.00 mcg,100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,1.167 mg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
"Eggplant, raw",0.00 mcg,100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,0.649 mg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
"Teff, uncooked",0,100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,3.363 mg,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
"Sherbet, orange",0.00 mcg,100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,0.063 mg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

In [ ]:
# verify_integrity
# To enforce uniqueness of index values
# verify_integrity=True --> If index contains unique values Else throws ValueError
# verify_integrity=False --> Index can have duplicate values (not recommended)
nutrition.set_index('folic_acid', drop=False, append=True, verify_integrity=False).head()

,,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,folic_acid,,,,,,,,,,,,,,,,,,,,,
Cornstarch,0.00 mcg,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,0.000 mg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
"Nuts, pecans",0.00 mcg,100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,1.167 mg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
"Eggplant, raw",0.00 mcg,100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,0.649 mg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
"Teff, uncooked",0,100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,3.363 mg,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
"Sherbet, orange",0.00 mcg,100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,0.063 mg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

In [ ]:
nutrition.calories.value_counts().head()

884    78
47     45
56     43
0      39
50     38
Name: calories, dtype: int64

In [ ]:
# nutrition.set_index('calories', verify_integrity=True).head()
#  we get ValueError: Index has duplicate keys

# Extracting from DataFrames by Label

In [ ]:
nutrition.head()

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,0.000 mg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,1.167 mg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,0.649 mg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,3.363 mg,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,0.063 mg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

In [ ]:
nutrition.loc['Eggplant, raw']
# we get a series of column values for that passed row index label

serving_size       100 g
calories              25
total_fat           0.2g
saturated_fat        NaN
cholesterol            0
                  ...
alcohol            0.0 g
ash               0.66 g
caffeine         0.00 mg
theobromine      0.00 mg
water            92.30 g
Name: Eggplant, raw, Length: 75, dtype: object

In [ ]:
type(nutrition.loc['Eggplant, raw'])

pandas.core.series.Series

In [ ]:
# If we only want to fetch the specific column value and not series:
nutrition.loc['Eggplant, raw']['calories']

25

In [ ]:
# If we only want to fetch the specific column value and not series:
nutrition.loc['Eggplant, raw', 'calories']
# using both dimensions: Row and column axes labels

25

In [ ]:
# We can also use slicing for Rows/Column/Both 
# Returns a DataFrame with consecutive lables(rows/columns)
nutrition.loc['Eggplant, raw':'Sherbet, orange', 'calories':'cholesterol']

                 calories total_fat saturated_fat cholesterol
name
Eggplant, raw          25      0.2g           NaN           0
Teff, uncooked        367      2.4g          0.4g           0
Sherbet, orange       144        2g          1.2g         1mg

In [ ]:
# We can also pass a list of exact Rows/Column/Both labels that we want to fetch 
# Can be used when the labels we want to select are not consecutive in our dataframe and hence, slicing can't be used
# Returns a DataFrame with the passed rows/column labels
nutrition.loc[
    ['Raspberries, raw', 'Blackberries, raw'],
    ['protein', 'vitamin_b6']
    ]

                  protein vitamin_b6
name
Raspberries, raw   1.20 g   0.055 mg
Blackberries, raw  1.39 g   0.030 mg

# DataFrame Extraction by Position

In [ ]:
nutrition.head()

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,0.000 mg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,1.167 mg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,0.649 mg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,3.363 mg,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,0.063 mg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

In [ ]:
nutrition.iloc[3]
# Using .iloc[] --> teh protypical way of extracting by position
# Returns a Series of column values
# is Zero-Based indexing

serving_size      100 g
calories            367
total_fat          2.4g
saturated_fat      0.4g
cholesterol           0
                  ...
alcohol               0
ash              2.37 g
caffeine              0
theobromine           0
water            8.82 g
Name: Teff, uncooked, Length: 75, dtype: object

In [ ]:
# Extracting specific row label index but all column values
nutrition.iloc[3,:]
# nutrition.iloc[3] ~ nutrition.iloc[3, :]

serving_size      100 g
calories            367
total_fat          2.4g
saturated_fat      0.4g
cholesterol           0
                  ...
alcohol               0
ash              2.37 g
caffeine              0
theobromine           0
water            8.82 g
Name: Teff, uncooked, Length: 75, dtype: object

In [ ]:
# Can also provide a list of row/column/both lable indexes that we want to fetch
# These labels we pass in list can be non-consecutive
nutrition.iloc[
    [4,6,9], :
]
# nutrition.iloc[[4,6,9], :] ~ nutrition.iloc[[4,6,9]]

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,0.063 mg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g
"Taro leaves, raw",100 g,42,0.7g,0.2g,0,3.00 mg,12.8 mg,126.00 mcg,0.00 mcg,1.513 mg,...,0.74 g,0.151 g,0.060 g,0.307 g,0.00 mg,0.0 g,1.92 g,0.00 mg,0.00 mg,85.66 g
Vegetarian fillets,100 g,290,18g,2.8g,0,490.00 mg,82.0 mg,102.00 mcg,0.00 mcg,12.000 mg,...,18.00 g,2.849 g,4.376 g,9.332 g,0.00 mg,0.0 g,5.00 g,0.00 mg,0.00 mg,45.00 g

In [ ]:
nutrition.iloc[[4,6,9], 2]
# Single column index passed:
# Returns a series

name
Sherbet, orange         2g
Taro leaves, raw      0.7g
Vegetarian fillets     18g
Name: total_fat, dtype: object

In [ ]:
type(nutrition.iloc[[4,6,9], 2])

pandas.core.series.Series

In [ ]:
# Using list of Row index as list (non-consecutive)
# Using slicing of column indexes (Consecutive)
# Returns a dataframe
nutrition.iloc[[4,6,9], 2:5]

                   total_fat saturated_fat cholesterol
name
Sherbet, orange           2g          1.2g         1mg
Taro leaves, raw        0.7g          0.2g           0
Vegetarian fillets       18g          2.8g           0

In [ ]:
# Boolean Masks:
# 2 list of booleans 
new_nutr = nutrition.iloc[
    [True if i%2==0 else False for i in range(8789)],
    [True if i%2==0 else False for i in range(75)]
]

In [ ]:
nutrition.shape # x rows y columns --> x*y observations

(8789, 75)

In [ ]:
new_nutr.shape # x/2 rows y/2 columns --> (x*y)/4 observations

(4395, 38)

In [ ]:
# Single value Extraction:
nutrition.iloc[9, 1]

290

# Single Value Extract with .at And .iat

In [ ]:
nutrition.head()

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,0.000 mg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,1.167 mg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,0.649 mg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,3.363 mg,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,0.063 mg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

In [ ]:
nutrition.loc['Nuts, pecans', 'calories']

691

In [ ]:
nutrition.iloc[1,1]

691

In [ ]:
# .at ~ .loc for single value extraction
nutrition.at['Nuts, pecans', 'calories']

691

In [ ]:
# .iat ~ .iloc for single value extraction
nutrition.iat[1,1]

691

In [ ]:
%timeit nutrition.loc['Nuts, pecans', 'calories']

7.48 µs ± 130 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [ ]:
%timeit nutrition.at['Nuts, pecans', 'calories']

3.85 µs ± 86.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

# Skill Challenge

1. Randomly select 10 food items and assign the resulting dataframe to a new variable called nutr_mini.

In [ ]:
nutr_mini = nutrition.sample(n=10)
#  nutr_mini = nutrition.sample(10, axis=0)
nutr_mini

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
"Chicken, roasted, cooked, meat and skin, back, broilers or fryers",100 g,300,21g,5.8g,88mg,87.00 mg,62.3 mg,6.00 mcg,0.00 mcg,6.718 mg,...,20.97 g,5.820 g,8.290 g,4.620 g,88.00 mg,0.0 g,0.92 g,0.00 mg,0.00 mg,53.52 g
"Beef, raw, choice, trimmed to 0"" fat, separable lean and fat, tri-tip roast, bottom sirloin",100 g,174,9.5g,3.5g,68mg,51.00 mg,86.2 mg,11.00 mcg,0.00 mcg,6.658 mg,...,9.51 g,3.493 g,4.724 g,0.438 g,68.00 mg,0.0 g,1.00 g,0.00 mg,0.00 mg,69.37 g
"Pie, prepared from recipe, blueberry",100 g,245,12g,2.9g,0,185.00 mg,0,23.00 mcg,18.00 mcg,1.194 mg,...,11.90 g,2.911 g,5.121 g,3.080 g,0.00 mg,0,0.70 g,0,0,51.20 g
"Snacks, cheese-flavor, popcorn",100 g,526,33g,6.4g,11mg,889.00 mg,15.3 mg,11.00 mcg,0.00 mcg,1.453 mg,...,33.20 g,6.410 g,9.700 g,15.370 g,11.00 mg,0.0 g,3.40 g,0.00 mg,0.00 mg,2.50 g
"KEEBLER, Mini Fudge Grahams Cookies, FUDGE SHOPPE, 100 Calorie RIGHT BITES",100 g,467,18g,11g,0,349.00 mg,0,67.00 mcg,0,2.400 mg,...,17.90 g,11.100 g,2.100 g,3.900 g,0.00 mg,0,0,0,0,2.50 g
"Chicken, raw, giblets, broilers or fryers",100 g,124,4.5g,1.4g,262mg,77.00 mg,0,345.00 mcg,0.00 mcg,6.662 mg,...,4.47 g,1.360 g,1.120 g,1.090 g,262.00 mg,0.0 g,0.99 g,0,0,74.87 g
"Pork, raw, separable lean only, bone-in, center rib (chops or roasts), loin, fresh",100 g,136,4.8g,1.6g,56mg,60.00 mg,57.9 mg,0.00 mcg,0.00 mcg,6.685 mg,...,4.80 g,1.617 g,1.999 g,0.524 g,56.00 mg,0.0 g,1.01 g,0.00 mg,0.00 mg,72.40 g
"Beverages, bottled, Cranberry-Apple Juice Drink, OCEAN SPRAY",100 g,56,0g,NaN,0,19.00 mg,0.4 mg,4.00 mcg,4.00 mcg,0.028 mg,...,0.00 g,0.001 g,0.001 g,0.001 g,0.00 mg,0,0.07 g,0,0,86.00 g
"SILK Very Vanilla, soymilk",100 g,53,1.7g,0.2g,0,58.00 mg,0,10.00 mcg,0,0,...,1.65 g,0.206 g,0,0,0.00 mg,0,0.65 g,0,0,87.41 g
KRAFT VELVEETA Pasteurized Process Cheese Spread,100 g,303,22g,14g,80mg,1499.00 mg,0,0,0,0,...,22.00 g,14.400 g,0,0,80.00 mg,0,6.00 g,0,0,45.80 g

2. From nutr_mini, extract the **total_fat** and cholesterol columns for all rows.

In [ ]:
nutr_mini.loc[:,['total_fat', 'cholesterol']]

                                                   total_fat cholesterol
name
Chicken, roasted, cooked, meat and skin, back, ...       21g        88mg
Beef, raw, choice, trimmed to 0" fat, separable...      9.5g        68mg
Pie, prepared from recipe, blueberry                     12g           0
Snacks, cheese-flavor, popcorn                           33g        11mg
KEEBLER, Mini Fudge Grahams Cookies, FUDGE SHOP...       18g           0
Chicken, raw, giblets, broilers or fryers               4.5g       262mg
Pork, raw, separable lean only, bone-in, center...      4.8g        56mg
Beverages, bottled, Cranberry-Apple Juice Drink...        0g           0
SILK Very Vanilla, soymilk                              1.7g           0
KRAFT VELVEETA Pasteurized Process Cheese Spread         22g        80mg

3. Extract all columns from vitamin_b12 column to the end, for the first, second and third rows.

In [ ]:
col_start_pos = nutr_mini.columns.get_loc('vitamin_b12')
nutr_mini.iloc[0:3, col_start_pos:]

,vitamin_b12,vitamin_b6,vitamin_c,vitamin_d,vitamin_e,tocopherol_alpha,vitamin_k,calcium,copper,irom,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
"Chicken, roasted, cooked, meat and skin, back, broilers or fryers",0.27 mcg,0.270 mg,0.0 mg,2.00 IU,0.27 mg,0.27 mg,4.9 mcg,21.00 mg,0.076 mg,1.42 mg,...,20.97 g,5.820 g,8.290 g,4.620 g,88.00 mg,0.0 g,0.92 g,0.00 mg,0.00 mg,53.52 g
"Beef, raw, choice, trimmed to 0"" fat, separable lean and fat, tri-tip roast, bottom sirloin",1.15 mcg,0.556 mg,0.0 mg,0,0.33 mg,0.33 mg,1.3 mcg,25.00 mg,0.067 mg,1.47 mg,...,9.51 g,3.493 g,4.724 g,0.438 g,68.00 mg,0.0 g,1.00 g,0.00 mg,0.00 mg,69.37 g
"Pie, prepared from recipe, blueberry",0.00 mcg,0.034 mg,0.7 mg,0,0,0,0,7.00 mg,0.067 mg,1.23 mg,...,11.90 g,2.911 g,5.121 g,3.080 g,0.00 mg,0,0.70 g,0,0,51.20 g

4. Get the calories for the third food in nutr_mini using an attribute-based approach that is faster than .loc and .iloc .

In [ ]:
col_index = nutr_mini.columns.get_loc('calories')
row_index = 2
nutr_mini.iat[row_index, col_index]

245

In [ ]:
col_label = 'calories'
row_label = nutr_mini.index[2]
nutr_mini.at[row_label, col_label]

245

In [ ]:
nutr_mini.iat[2,1]

245

# More Cleanup: Going Numeric

In [ ]:
nutrition.total_fat.head()

name
Cornstarch         0.1g
Nuts, pecans        72g
Eggplant, raw      0.2g
Teff, uncooked     2.4g
Sherbet, orange      2g
Name: total_fat, dtype: object

In [ ]:
nutrition.total_fat.sum()

'0.1g72g0.2g2.4g2g0.3g0.7g23g24g18g0g0.4g0.1g7.2g15g4.5g16g0.4g0.9g9.2g0.5g1.7g5.9g33g15g0g0g3g0.4g68g1.5g0.2g11g0.8g16g0.2g0.5g50g0.3g0.6g3g16g3.1g11g2.4g0g0.3g0.5g99g0.1g5.3g5.3g0.4g5.3g0.2g0.3g6.4g22g1g14g10g17g14g4.3g22g36g0.7g100g27g2.8g5.8g14g0.7g1.5g11g34g0.2g0.9g4.6g0g0.4g19g0.2g10g28g6.7g6.7g0.3g0.3g44g37g14g50g0.9g0.7g0.1g0.7g8g10g19g9.2g0g0.2g8.6g1.3g14g0.4g0.2g8.2g5.2g3.3g2.1g0.1g80g0.5g1.4g0.4g3.3g0.2g0.7g0.1g9.4g0.3g0.6g29g0.2g1.4g0.2g0.4g1.2g1.8g0g0.9g0.2g1.4g0.8g1.5g9.8g0g13g16g19g7.4g0.2g5.2g29g0.3g9.9g22g14g15g4.1g0.5g3.5g15g20g32g1g81g0.2g1.6g0g17g22g7.1g7.4g0.2g8.7g1.4g34g0.3g6.3g30g8.1g0.2g0.1g3.7g0.6g0.3g3.9g0.3g1.2g29g14g26g1.1g2g13g0g9g22g3.7g100g0.1g2.1g2.1g0.3g0.2g6.8g8.1g8.3g2.4g0.2g23g6.7g1g0.3g0.2g0.1g12g17g0.1g100g3.4g0.2g6.7g1.5g22g0g1g25g34g3.6g100g7.3g9g1.6g0.4g0.3g18g0.4g9.5g1.4g11g3.1g1.5g0g2.4g3.6g0g15g1.2g6.6g0.7g4.2g15g0.1g0.5g0.2g0.1g3.5g3g0.1g0.4g0.1g0.3g100g31g2.8g9.7g2.3g11g1.7g0.1g1.7g0.5g4.7g0.5g0.2g8.6g18g25g0.5g0.5g26g7.7g0.1g0.1g100g1.1g16g2.4g0.1g21g7g0.3g0.3g19g1.2g1.9g28g0.6g0g100g6.4g2.2g0.1g0.4g1.4g3.4g9.6g23g9.6g21g1.5g0g0.5g8.9g0g0g22g22g0.3g1.1g1.1g0.4g42g2g100g15g51g0.4g0.7g0.4g0.8g7.2g1.9g0.3g0g24g1.2g0.2g13g7.3g25g16g0.2g4.3g22g18g26g2.8g0.9g0g0g4.8g1.5g15g3.4g8.7g0g0.2g1.6g1.8g0.6g100g100g0.2g0.2g0.1g2.7g1.6g9.6g27g31g7.4g0g0.5g0.3g0.8g9.7g1.7g4.3g0.6g15g100g9.8g2.1g0.6g0g0.5g0.1g0.7g13g0.2g44g10g8.1g11g0g0.3g13g4.7g13g2g0.5g24g0.2g11g0.2g0.5g0.6g27g0.7g0.9g4.6g0.1g0g4g2.7g1.9g0.2g1.1g6g0.7g6.1g21g1.3g8.4g6.7g0.2g0.8g100g9.3g0.2g0.3g30g0.1g31g1.2g100g0.2g0.4g0.9g0.1g0g11g16g17g6.2g0.1g24g59g6.1g4.9g0.3g30g2.7g33g29g100g4.4g0.2g15g13g30g5.9g0g2.2g100g6.6g0.3g13g0.3g0.4g0.1g0.6g4.9g0.3g0.2g0.1g0.3g1g0.5g16g0.1g5.6g1.3g0.7g0.1g0.6g5.3g5.9g0.1g2.4g0.5g42g32g30g31g81g100g14g0.2g0.2g4.4g3.5g0.6g3.4g0g14g100g100g0.4g0g3.1g1.9g0.4g0.8g2.3g27g7.4g0.3g0.2g11g18g1g0.9g1.1g1.1g0.3g0.3g0.6g1.2g0.2g0.4g11g100g0.7g26g0.1g0.4g0.4g30g0g0.1g26g35g50g0.1g0.6g0.2g3g0.1g3.5g100g0.4g0.4g0.1g4.3g1.5g8.6g0.3g0.2g0.6g5g32g34g20g0.3g0.9g7g0.9g21g3.1g0.1g31g27g0.4g29g28g0.3g1.7g0.6g0.2g0.1g0g100g100g100g0.1g0.2g0.5g0.1g0.2g0.9g0.1g0.1g0.1g3.2g28g21g0g0.1g1.7g0.6g0.3g99g2.5g17g4.3g0.7g0.3g0.4g0.7g0.4g100g100g6g1.1g100g0.3g0.1g0.3g0.3g0g0.7g0.7g0.2g0g0.3g100g20g0.7g0.4g0.5g0.2g1.8g0.2g2.1g1.3g0.4g4.2g21g100g100g0.2g100g0g0.1g9.7g0.6g100g3.3g1.8g0.2g10g0.1g0.3g2g0.2g6g3.4g100g100g2.1g1.6g0.7g0.9g0.2g0.2g0.3g2.3g0.1g9.7g0.2g100g0g4.2g0.1g11g11g0g11g1.7g3.3g100g6.9g6g0.1g4.3g1.1g1.2g2.5g13g2g14g0.4g3.8g9.5g15g100g1.8g30g18g20g30g14g26g1.4g0.2g20g13g5.2g6.4g4.3g4.2g16g37g0.3g11g0.3g13g0g0.9g27g12g1.2g0.8g3.4g0.3g0.8g12g10g1.1g30g4.3g4.3g0.6g18g0.4g24g5.9g0.1g28g5.5g18g0g8.8g50g100g1.9g8.9g5.2g12g4.8g4.3g0.5g1.7g14g25g13g4.4g11g13g0.5g23g3g2.5g7.3g25g17g4.4g14g7.6g7.2g5.8g20g0.4g0.1g2.4g6.3g0g0.2g2.1g7.2g2.3g3.2g0.9g0.1g0.8g0.9g55g19g2.5g13g0.1g9.3g100g0.5g0.2g9g23g20g5.9g6.3g5.1g25g13g0.1g0g0.1g36g5g3.6g2g0.6g1.9g1.1g18g0.7g1.9g0.2g30g0.4g5.8g0.3g12g0.7g4g7.1g22g20g31g36g34g1.6g3.4g1.2g13g12g30g18g0.1g2.6g5.5g3.1g0.2g8.8g1.2g3.5g6.3g3.2g5.2g100g22g7.2g4.8g2.3g0g0.7g0.2g3.2g0.5g5g0.1g2.7g0.1g10g1g14g21g0g1.5g4g2.2g0.3g21g52g5.6g0.3g3g6.7g0.2g0.4g0.2g0.2g1.1g0.1g0.4g13g4g8g1.8g0.5g0.1g1.2g12g0g0.6g0.5g17g100g0.1g3.8g2.5g2.7g2.7g2.9g4.5g3.3g28g5.1g5g4.3g20g28g30g26g0.1g0.3g0g3.8g29g2.2g6.9g59g4.9g0.5g16g25g11g4.7g2.2g14g0.5g6.5g17g30g0g3g6g0.1g1g1.9g1.7g50g13g6.7g1.5g24g24g1.1g0.1g11g0.1g0.4g4.9g12g28g21g31g19g13g16g28g4.9g13g15g81g3.3g3.1g0.3g14g17g61g4.2g0g0.2g9.5g8.2g19g26g30g8.8g31g0.1g50g0.1g12g51g4.4g0.6g0.5g0.3g14g5.2g10g0.8g0.2g0g0g0.2g78g2.4g0.6g26g2.5g14g0.1g26g0.2g8.1g7.3g0.3g1.2g0.9g3.3g2.2g100g10g4.4g10g2.6g14g8.7g27g0.3g14g3.3g4.7g0g15g4.8g2.9g1.7g4.7g16g15g0.1g10g2.7g2.8g29g15g3.3g3g34g0g12g0.2g29g0.1g3.7g4g1.2g1.7g0.2g1g33g1.3g1.1g32g9.5g0.3g15g1.2g14g2.4g4.4g27g0g7.4g0.1g0.3g0.6g2.2g8.9g12g24g20g6.1g12g3.3g0.1g12g5g0.7g76g27g16g2g0.7g0.3g45g15g0.5g31g5.2g9g11g14g0.1g3.6g0.1g0g1.2g0g18g40g1.7g1.7g0g0.2g9.7g0.3g23g15g1.3g89g23g0g7.7g19g8.1g19g21g5.9g24g29g6.4g15g0g12g1.1g15g34g28g1.6g13g7.5g2.3g3.9g6.5g0.7g0g0.7g6g0.2g9.1g0.8g22g0.5g2g1.2g1.2g3.1g0.5g23g4.8g3.6g0.7g26g10g3.3g25g33g38g23g21g13g32g13g64g8.7g5.5g11g0.5g0.5g2g0.7g19g7.1g20g0.2g0g0.2g0.3g2.3g0.3g1.7g31g1.4g2.8g1.4g100g11g0.7g1.7g28g3.8g34g0.1g3.2g9.7g0g0.5g16g0.2g15g15g12g0.2g21g2.3g3.2g1.4g7g5g1.2g4.4g9.5g0.7g2g0.5g1.2g0g17g2.6g0.1g0.3g0g44g0g2g0.3g8.6g0.1g0.6g0.3g49g1.2g35g49g0.2g1.6g32g1g30g12g0g36g3.5g6.1g0.3g17g15g6g3.8g20g7g1.2g0.8g0.4g16g0.1g0.2g53g14g8.1g0.2g29g4.4g4.8g4.4g0.8g4g1.7g53g0.1g57g29g0.1g1.7g0.4g2.4g22g5.8g0.4g5.4g33g16g22g0.3g15g17g0.6g36g21g0.1g0.1g0.2g14g0.1g0.2g2.9g0.4g7.1g3.4g0.3g0.5g4.6g2.7g7.2g1.4g0.5g11g25g2g0.2g25g0g7.5g0.6g0.9g0g3.9g0.1g65g5.5g4.2g36g0.2g9.5g30g0.4g13g2.9g8.4g0.9g5.1g0.2g4.8g15g0g26g0.5g18g10g6.7g49g48g0.6g44g38g1.4g31g7.4g1.6g0.5g18g0.2g25g1.9g1.6g1.5g11g18g13g6.4g34g6.2g0.1g3.5g1.2g20g3g9.5g0.1g1.7g3.3g0.8g20g2.2g0.1g0.4g3.7g0.3g0.5g0g1.4g0.4g0.6g23g0.9g1.8g78g67g2.6g3.3g14g14g0.6g5.9g70g4.4g0g0.3g12g0.4g2.6g9.8g18g14g4.2g0.1g2.1g0.2g2g1.6g26g3.6g6.8g23g8.7g10g24g3g19g30g16g0.6g17g3.7g10g14g0g0.1g0.8g0.1g24g20g27g1.2g33g2.4g0.3g12g12g9.3g30g1.8g0.7g11g0g2g0.3g15g0.1g7g0g0.3g4.2g4g0.1g2.1g12g1.4g5g14g0.1g0.3g55g4.3g14g0.3g18g66g34g15g30g6g4.3g0.9g0.4g28g0g0.2g0.2g8.7g0.2g0.1g28g12g7.6g0.3g0.1g12g0g12g20g1.4g0.2g0.3g0g2.2g0.2g0.9g100g38g0.9g6.4g1.5g0.7g1g1g3.2g0.4g9g0.2g7.9g0.4g1.7g0.6g0.8g25g2.5g0.2g54g0.1g16g25g16g24g10g20g0.1g6.2g2.5g5.3g100g43g21g14g12g5g20g0.1g0.7g0.2g1.2g19g1.9g2.8g14g1g0.7g3.4g18g0.8g53g2.7g19g0.2g12g2.1g3.1g16g0.7g0g22g6.3g8.3g0.2g9.1g10g11g17g4.6g4.4g31g12g0g0.2g2.6g13g24g7g1g0.5g1.5g0.4g1.3g24g0.1g6.1g0g50g0g1.7g0.3g14g1g13g1.2g0.7g0g0.3g0.1g22g3.7g0.6g0.2g0.2g0.9g1g7.9g3g0.1g29g5.6g2.8g1.3g8g0.5g44g0g15g0.1g100g0.9g0g12g99g0.1g0.2g0.3g5.3g9.2g21g17g0.4g1g33g1.5g0.4g31g0g0.3g13g3.9g10g1.3g0g6.6g7.9g0.3g0g0.4g0.1g0.5g6g0.7g0.2g1.2g22g13g2.4g13g1.5g5.3g7.7g26g79g7.2g9g0.9g2.3g2.6g20g8.6g2g0.2g3.3g6.3g1.3g0.8g10g22g30g0g14g16g26g0.1g19g19g18g11g1.5g6.9g14g0.2g20g0.1g2.7g8.7g22g11g1.2g13g11g13g0g4.7g30g22g0.6g0.1g0.8g1g0.2g23g20g0.7g0.6g26g4.8g9.3g0.3g0.5g20g0.6g3.2g4.8g2.2g0g3g10g6.3g5.4g1.8g0.2g2.4g0g26g8.8g0g17g1g6.2g46g25g0g12g18g0.1g0.7g29g4.2g20g0g8.5g0g26g0.2g0.2g0.3g15g0.2g0.2g0.5g0.2g0.7g0.1g62g5g12g8.6g2g3.2g0.3g0.5g35g4.7g0.1g0g24g0.7g25g0g4.5g2.1g0.9g2.7g18g18g9.2g1.4g31g3.9g0.1g1.8g1.5g3.5g20g0.1g7.4g5.5g0.6g29g0.9g5g12g0g0g0g0g0g24g16g18g0.1g11g5.6g3.9g2.7g1.7g0.7g2.1g1.1g0.2g0.1g0g3.5g0.4g20g0g2g3.5g1.4g2.3g1g5.9g19g55g0g0g7.9g1.9g0.6g0.1g0g7.7g66g0.2g0.4g0.5g13g1g22g9.6g30g1.6g17g7.5g0.2g0.1g3.9g16g13g0.2g6.2g9.1g32g0g24g25g0.4g0.9g21g24g1.1g15g1.7g53g3.8g0.4g0.1g21g12g0.3g1.6g4.9g6.6g3.5g7.2g0.1g0.2g10g4.2g3.3g30g4.7g29g16g2.6g1.6g1g1.5g1.1g8.4g2.7g0g0g2.5g7.1g2.5g6.5g0.2g0.1g12g1.2g3.9g0g26g2.7g14g4.9g19g0g19g27g2.4g11g1.4g0.6g0.3g18g0g33g0.8g12g1g9g12g0.2g16g28g9.1g5g16g2.1g0.4g13g1.5g44g3.4g0.4g5.1g2.1g18g0.1g0.2g0.1g5.1g9.2g13g1.4g0.6g0.5g3.4g4.6g15g100g23g27g22g3.7g16g0.9g1.1g1.1g23g12g17g18g7.1g9.6g3.8g0.5g40g61g21g35g0.1g4.1g52g16g2.3g2.5g3.1g17g11g3.9g0.6g1.4g0g0.5g6.5g22g0.3g16g16g24g2.7g0g0.5g2.7g0.1g0.1g1.2g19g17g0g3.8g11g0.3g4.3g1.1g2.9g2.5g100g3.6g20g3.1g15g14g10g2.1g1.3g2.6g0.4g0.1g4g5.8g0.1g15g18g26g24g26g0.2g0.5g12g0.9g6.9g0.2g10g3.8g12g3.1g2.6g2.1g2.8g10g3.9g1.1g0.1g1.1g21g24g4.6g3.7g0g13g0.4g4.4g1.9g4.1g19g12g12g2.7g22g2.6g3.2g100g0.4g4.5g4.4g3.3g0.4g3.3g1g0.5g14g15g0g0.4g2.4g1.1g0.4g50g8g1.7g17g16g3.2g50g1.8g0g45g0g21g24g23g15g7.6g19g18g5g0.1g3.3g17g6g17g25g0.1g4.4g4.9g28g0.1g0.3g21g0g4.1g27g4.2g16g34g7.7g3g29g24g14g15g2.1g2.6g24g5.4g4.9g1.6g3.7g29g2.3g0.1g0.2g6.6g2.7g1.9g2.8g5.6g15g12g9.3g12g9.1g5g14g13g0.3g0.2g29g1.2g34g0g18g34g25g0.3g24g3.5g0.6g3.7g1.6g0.2g1g100g8.5g12g28g3.7g35g25g22g0g12g0.1g1.5g15g10g40g27g1.1g6.5g6g3.7g2.7g6.4g2.5g24g0.1g12g2.9g0.2g0g1.7g15g19g19g0g1.6g18g26g34g27g18g2.6g15g34g0.1g13g0.7g2.8g13g0.8g1.2g0g0g43g8.8g16g0.2g5.7g0.2g10g0g0.4g16g39g0.5g0.8g0.6g1.4g9.1g7.1g19g14g9g26g0.2g8.3g100g26g0.1g21g4.4g2g0.8g3.1g0.1g2.9g8g0.9g4.6g4.4g13g0.1g2.1g30g15g0g0.8g0.9g6.9g0.1g0.1g8g5.3g26g51g18g9.5g29g2.8g0g14g0.3g0.1g11g0g4.2g14g27g1.1g1g0.6g15g16g18g0g1g23g18g14g1.7g0.9g12g1.8g23g0g0.8g2.8g8.2g1.3g15g0.1g10g41g0g7g52g29g3.2g1.8g0.2g0g0.8g0.1g0.7g3.6g22g0.2g2.4g0.9g1.2g0.1g25g5.4g8.1g13g2.6g48g5.1g2g0g0.1g14g94g5g2.3g61g14g4.5g0.3g3.5g71g22g30g0.1g0.2g1.2g1.9g1.2g23g0.5g0g1.6g50g2.4g0.9g18g0g35g12g0.2g13g7g0.1g0.3g0.1g0.5g0.5g0.1g13g47g32g1.9g2.1g31g2.9g0g1.4g10g0.2g1.6g0.7g0g16g19g28g1.6g4.4g9.7g1.7g26g33g0.4g1.8g0.1g0g0.2g19g5.2g1.1g4.9g0.3g100g3g1.1g19g50g3g34g14g31g0.4g11g8.5g13g0.4g0.2g16g2.9g0g0.1g61g9g7.6g9.7g18g0.4g2.2g0.1g0.2g18g34g5.3g7.2g5.8g48g0.2g0.5g6.7g9g0.8g0.1g26g0.6g12g0.1g7.3g4.4g2.1g11g11g1.8g24g1.5g2.2g1.8g18g6g0.3g4.7g1.6g0.3g1.1g4.6g0.7g1g0g14g14g0.2g2g18g1.1g0.1g10g15g0.2g8.4g22g1.8g17g0.3g6.8g16g14g0.1g0.2g9.1g2.5g25g36g19g0.1g0.9g29g8.3g3.1g7.4g22g2.1g8.7g9.3g0.4g1.7g0g27g18g23g0g3.2g7.7g3.7g0g0.2g33g4g22g19g4.6g52g0.1g1.2g43g38g14g7.1g0g3.3g0g21g0.7g8.7g0g3.9g3.1g32g0g0.3g20g1.2g18g0g0.1g4.8g5.3g2.5g1.7g0.5g38g19g4.7g42g0.4g0.4g0g0.1g2g11g15g27g25g2.9g3.3g24g0.8g0.4g0.1g10g0g0.3g0.4g2.7g2.2g16g18g5.2g0g35g31g31g51g12g0.6g35g6.1g0g5.6g53g9.5g0.7g7.4g0.2g2.6g0.9g3.8g100g100g100g1.2g23g2.7g15g5.6g31g12g3g32g25g3g1.3g1.3g3.4g4.3g3.8g22g13g16g17g2.5g2.7g0g13g2.2g2.1g12g8.7g0.2g15g24g3.3g3.9g3.9g24g0.3g75g0.8g14g1.4g1.8g9.8g34g1.2g25g3.7g10g12g0g0.3g0g18g19g14g2.4g0.2g2.8g6.9g3.8g0.3g0.5g0.2g0.1g1g2.3g0.1g0.2g4.9g0.3g13g5.9g27g3.7g5.5g0.1g0.1g13g16g0g9.5g0.2g0g0.3g0.1g7.1g2.7g22g1.7g15g7.3g24g4.4g16g0.1g0.3g9.8g0.1g28g31g32g2.4g11g27g12g18g0.2g20g6.3g24g20g0.5g1.4g50g16g5.1g24g12g1g8.4g2.5g20g18g4.6g18g0g0g8.6g0g0g21g0.2g8.2g7.5g3.5g100g3.6g5.2g16g0.3g4g0g12g34g19g21g1.7g3.5g23g0.1g4g1.9g0.2g0.2g0.5g6.7g3.3g0.1g12g0.1g11g3.2g2.3g3.6g0.2g23g0.3g0.6g1.1g0.1g3g8.5g27g17g8.2g1.9g3.4g8.8g1.5g0.4g2.5g9.5g0g9.4g0.2g0.7g0.7g3.5g4.1g7.5g6.2g0.2g18g0g14g8.2g11g1.2g0.1g7.6g11g1.2g16g0g0g2g0.6g2.4g24g17g0.5g0.6g2.4g4.6g5.8g0g0.5g37g11g0.1g6.3g0.1g13g17g4.2g3.3g1.2g2.5g0.2g0.2g0g29g12g0.1g0.8g6g0.2g0.3g2.8g0g1.4g0.3g5.7g10g25g0.1g3.2g50g10g19g6.3g13g21g29g0.1g53g9.3g51g49g6g25g8g25g8.7g32g3.1g9.1g16g0g3.7g13g11g0.2g2.2g33g0.7g8g0.1g0.4g0.1g1.7g3.7g4.9g0.5g7.5g0.6g37g3.3g27g1.4g0.6g10g8.1g1.3g61g25g1.2g1.9g2.6g0.4g0.1g0.3g3.4g8g2.4g55g53g27g0.4g0.1g6.9g22g29g0g0.3g0.2g26g23g0.7g3.9g33g0.4g13g0g4.9g0.4g0.5g0.2g17g1.2g0.3g0g0.2g0.6g14g7.2g0.1g14g22g12g31g1.3g0.3g1g13g13g4.6g39g0.4g0.4g0.1g16g0.8g3.7g21g17g0.2g0g56g23g8.8g21g0g0g0.7g29g0.2g15g12g9.3g12g16g10g0.2g0g3.8g0.3g0.2g0.8g0.9g19g0.9g28g22g0.2g19g5.1g30g2g0.8g0.4g5.2g0.1g20g53g17g19g30g100g8.2g49g0.1g0.2g1.1g0.9g53g10g0.9g0.7g5g4g74g3.4g2.5g3.4g0.4g11g24g0.8g4.3g1.5g20g24g22g0.8g53g75g3.1g18g10g15g0.2g2.1g26g2.7g3.2g55g8.2g0.1g15g23g1.5g3g0.6g0.9g16g3.3g8.1g0.2g0g0g2.4g0.9g1.8g1.5g3.5g7.5g37g4.1g16g5.4g2.3g1.6g5.7g30g8.7g5.3g0.3g5.9g4.5g12g1.3g1.6g0.1g18g7.8g5.3g0g3.5g13g27g23g33g18g32g0.2g1.8g4.8g55g23g0.1g25g22g0.2g0.9g0.2g4.6g6.1g0g0g19g1.2g2.8g4.6g6.1g0g8.9g9.7g20g0.1g32g100g0g21g4.1g0.8g25g0.2g0.2g2.3g0.1g9.3g3.4g0.5g25g15g3.7g0.5g38g42g3.9g18g13g0.1g25g0.1g0.1g0g27g1.5g6.9g44g4.5g0.2g18g9.2g20g5.1g25g0.7g14g3g0.1g7.5g0.1g1.8g0.3g0.8g0g13g7g1.8g0g0g0.9g7.2g9.4g27g21g15g0.4g4.6g27g10g3.5g4.1g20g18g18g0g0.2g23g3.6g4.6g1.3g20g3.8g22g5.7g16g17g0.9g0.9g1.5g22g22g10g0.3g19g0.3g0.6g6.3g0g0.9g4.7g3.5g0g0.9g0.9g2.5g31g8.2g2.2g0.4g0g27g19g15g0g84g7.5g0.1g0.6g0.5g8.4g13g26g1g4.5g0.3g0.3g1.7g5g11g20g5.6g14g0.4g0.2g12g0g49g13g51g39g38g29g17g0.1g12g11g10g3.8g5.8g0g25g0.2g7g3g12g4.2g3g17g17g6g16g0.3g12g14g9.2g0.1g1.1g8.9g3.5g12g19g100g24g0g3.9g100g4.9g0.2g4.2g9.6g2.7g0.3g4.8g0.9g3.4g0.3g0.4g3.8g24g17g51g1.4g1.9g1g6.1g1g5.4g2.9g17g3.8g1.9g18g6.3g1.2g24g0.2g0.2g0.6g2.3g21g23g0g0g6.6g58g1.3g2.8g5g0.4g0g0g4g4.1g4.1g4.4g12g0g24g0.9g1.8g0.1g28g16g3.4g16g0.7g26g0.7g11g1.6g0.2g14g2.5g0.2g12g12g1.6g5g0.9g5g0.7g6.4g3.5g3.3g5g20g70g0.3g1.3g7.5g1.4g0g49g0.2g0.7g1.7g100g16g0.2g10g0.2g12g5.3g0.6g0.3g14g25g3.4g0.8g4.5g2.8g17g0.4g1.6g6.9g0.2g1.5g26g18g3.6g0g0g7g20g0g11g2.8g34g17g0.1g0.1g7.6g0.7g22g0.9g4.3g16g0.1g6.3g8.7g8.1g13g2.1g7.5g14g3.4g5g28g0.6g17g3.1g2.7g10g4.9g3.1g2.2g3.1g13g8.6g22g26g0.1g25g1.2g7.5g0.2g23g81g25g0.1g1.6g1.9g0g0.1g0.5g24g18g0g0.4g3.7g18g15g2.1g0.5g0g0.7g3.6g12g0g12g1.8g24g5.4g1.7g0g0.2g19g2.8g3.4g0.2g1.3g0.9g0.3g7.5g20g3g16g0.1g24g8.1g0.2g0.8g0.4g5.6g20g0.3g1.7g3.3g1.5g0g0.1g0.9g0.9g0.1g0.5g1.3g5.7g4.1g0g12g1.2g12g7.2g3g22g0.5g1.5g5.5g17g4.2g0g1.1g37g0.8g0.2g13g14g2.3g0.1g0.2g0.3g6.6g15g0g5.2g11g1.2g2.7g8.1g7.3g7.6g2.1g1.6g0g13g0g8.6g7.8g2g5.6g0g6.3g12g11g0.3g6.9g9.2g0.2g0.2g0.8g5.4g0.3g2.1g19g9.3g44g7g0.3g0g3.5g6.9g38g0.5g0.4g13g0.1g12g61g13g1.3g8.2g13g0.6g1.2g3.4g0.1g6.1g0g7.5g14g15g2.6g1.8g7.4g0.2g0.4g4g0.9g0.2g0g6.9g2g9.1g2.5g2.7g0g0.2g27g0.1g2.9g2.8g10g1.4g0g0.7g5.7g4g5g47g15g32g1g7.6g5.3g12g0.2g0.1g0.6g1g1.7g2.1g0.1g69g2.3g0.2g12g8.3g0.1g7.8g7.4g0.2g1.8g0.2g23g1g0.1g3.8g26g1.8g10g0.3g1.6g1.4g15g1.5g5.2g48g32g32g2.7g0.3g0.9g3.6g1.5g9.2g2.1g20g3.6g0.5g0.7g0.5g0.8g0.1g0g15g0.5g18g3.4g0.1g0g0.1g21g68g0.3g2.6g2.3g4.9g7.6g0.2g4.6g22g2.5g100g13g0.6g8.6g8.2g32g0.3g1.9g0g4g0.6g1.8g8.3g30g0g0.1g0.9g19g1.8g0g0g0g0.6g0g6.8g6.4g3.7g100g9.9g27g0g12g0.3g10g3.9g3.6g2.1g6.8g0.2g1.4g12g9.6g0.1g0.2g17g46g48g0.1g11g1g9.5g6.7g56g19g7.4g2.4g13g0.4g2.1g0.6g4.2g2.1g20g0g0.3g8.1g0g0.9g0g0.9g0.6g7.5g4.6g1.3g21g14g12g36g1g4.9g16g30g3.7g1.8g0.4g0g0.2g4.5g9.5g22g6.4g16g3.5g0.1g1.4g0.4g0.1g0g0g94g0.1g55g53g4.8g1.1g2g25g22g1g0.2g0.1g1.7g2.4g22g1.4g1.9g0.2g0.9g0.1g5.2g5g0g0g23g2.7g2.9g4.8g2.2g14g14g25g0.1g1.4g2.5g49g3.5g11g26g12g0.4g0g1.7g3.9g39g4.3g0g0.4g4.6g7.8g7.8g0g2.3g7g24g31g7.9g7.7g0.1g0.2g44g37g0.4g0.4g1.2g11g0.1g0g11g7.6g36g39g0.2g1.3g0.8g0.5g8.7g0.6g0.1g2.5g0.3g1.6g0g13g6g30g14g19g0.1g0.1g0.3g0.6g24g1.7g0.3g10g0g0.1g0.1g0.2g14g0.3g3g20g0.3g1.6g2.3g3.7g1.8g11g4.7g6.7g0.2g12g45g24g22g1.3g12g0.2g0.5g1.7g4.4g0.3g0g0g0.1g4.2g1.6g0.1g5.5g0.3g0.2g9g0.9g1.6g6.6g0.9g21g29g2.9g1.9g19g5g12g0.8g0.4g0g2.3g9.8g24g2.7g18g3.2g11g27g0g1.6g0g0g8.3g0.1g4g3.5g0g0.1g0.5g1.8g3g0g0.2g3.4g1.6g7.9g6.5g0g1.6g2.6g0.2g0.3g0g0g7.6g0.1g44g20g3.7g7.4g0.1g0.2g2.1g4.3g19g25g18g4.6g2.1g2.7g3.6g26g25g4.8g0.9g19g100g100g33g26g3g15g11g0.3g7.4g4.5g0.3g0.7g2.6g1.4g2.3g28g13g1.1g11g5.7g55g1g75g74g1.9g2g0.5g0.9g0g5.3g3.6g4.6g18g0.2g0.2g99g0.1g15g7.5g4.3g2.2g0g15g4g12g7.8g24g4.1g0.2g8.5g0g10g53g50g0.2g1g1.5g5.5g49g1.8g1.6g0.5g5g48g8.2g7.2g2.9g2.3g1.5g0.2g0.4g18g4g23g25g1.5g1.9g35g34g23g0.5g31g0.1g0.1g1.3g1.2g0g2.1g25g0.1g58g1.8g7.2g11g4g12g1.6g5.8g0.5g11g10g21g3.4g1g72g12g26g3.5g1.9g79g8g0g0.6g1.9g13g0.2g0.4g6.2g29g2.6g8g8.7g100g33g27g0.1g0.5g9.6g6.9g26g0.1g4.4g3.6g13g25g5.1g65g0.7g0.1g2g0.3g0.2g69g13g31g19g0.2g78g18g13g70g9.4g0.3g0.3g0g24g0.2g0.1g5.6g5.1g35g0.1g0g21g7.5g1.5g8.5g7.6g1.6g17g0.1g6.4g3.8g0.2g2.2g4g10g0.1g20g0.1g5.3g3.4g0g0g0.1g36g16g0.5g16g1g28g35g0.2g27g0.6g10g1g29g3.5g100g0.4g20g25g22g0.4g2.1g7.9g0g5.3g0g17g0g0g43g0g0g3.7g7.5g0.2g12g1.4g1.1g6.5g0.1g12g8.1g13g0.1g18g6.5g2.4g2.9g1.6g35g2.7g35g0.6g0.9g33g45g0.8g1.3g70g2.1g49g0.5g3.4g2.7g5.3g1.7g0g8.7g17g20g0.3g0.4g0.6g12g4.4g11g5.5g0g0.2g0.4g12g0.1g7.2g22g51g51g27g0.2g13g1.4g2.4g11g9g3g0.2g4.2g0.5g0.1g0.2g2.9g14g6.2g1.6g57g0.1g9.8g0g3.4g44g3.3g2.9g1g0.6g0.1g4.6g7.1g2.5g0.3g0.4g7.4g1.9g3.5g1.6g5.6g2.8g0.5g19g0.7g16g3.2g1.6g3g4.3g11g23g0.2g3.2g16g3g9.3g3.2g0.2g32g21g22g0.2g11g16g4.5g26g0.1g3.6g15g0g13g6.6g0.2g1g100g0.3g3.5g3.5g9.8g0.2g3.5g0g12g0.7g21g12g64g0.5g2.8g1.2g0.6g0g36g11g3.4g0.1g8.4g6.5g6.2g0.1g0.1g2.3g15g0.4g0.1g4.1g25g13g14g2.2g24g3.6g0.7g0.4g53g0.4g0.3g8.8g0.4g6.1g17g0.2g0.1g0.2g7.1g0g0.3g16g3.4g0.1g2.3g1.6g0.6g11g4.7g22g9.8g1g4.9g25g2.7g0.1g36g11g23g19g0.4g0.1g4g1.4g9.8g8.5g14g0.1g11g6.4g12g17g30g28g1g2.4g0g0g16g3.9g55g0g3.3g0.3g0.5g2g0.4g3.5g8.7g69g0g4.8g10g0.1g0g18g37g0.1g0.2g1.3g2.1g6.8g1.1g3.6g11g11g1.5g1.5g4.8g0.3g0.2g0.4g16g4.1g13g9.8g0.3g3.4g0.5g0.1g7g19g9.1g0g14g0.1g4.6g5.6g0g0.6g0.1g34g0.2g0g4.6g9.1g42g15g0.3g0g0.2g20g0.9g29g0g1.3g25g12g0g0g31g0g0.2g3.7g8.4g14g13g14g13g0.9g6.6g19g5.3g3.2g3.1g0.2g1g3g8g0.1g2.9g16g0g1.9g3.3g0g8.3g1.8g1.3g28g6g0g8.3g0.5g2.9g13g0.2g2.4g19g0g20g3.7g9.6g76g1.2g23g24g31g29g19g12g0.2g46g0.2g0.2g5.7g46g48g7.8g5.7g0.4g0.2g0.3g28g29g0g13g16g23g0g4.7g23g2.1g2.1g20g33g0g0.8g11g0g3.1g16g1.6g72g4.4g0.4g3.1g9.5g0g0g23g24g30g0.2g2g0.4g18g100g27g1.5g16g0.1g9.8g2.8g0.5g21g76g0.6g0.2g1.6g0.2g2.7g0.1g0.1g5g1.5g13g0.2g0.5g0.2g0.1g0.1g2.1g0.2g2.7g1g5.9g4.4g4.1g0.4g5.9g35g6.7g4.8g2.8g2.9g2g6.8g0.3g13g33g26g3.4g1.7g1.3g2.3g0.3g11g3.7g39g0.6g1g0.2g3g3.1g0.2g13g0.8g0.9g1.1g4.3g0g2.9g15g0g0.3g21g0.9g2.2g11g3.2g12g11g0.1g16g3.7g0.8g0.1g2.1g18g25g0.7g11g28g0g0.2g0.6g0.1g16g0.1g12g0.6g19g3.4g4.2g20g19g6g0.3g1.4g99g52g2.6g0.9g0.2g10g4.7g0g19g5.1g0.1g0g0.4g2.9g0.1g1.2g0.1g0.2g13g8.8g17g0.4g6.3g0.7g15g39g21g0g21g3.5g17g7.2g0g0.1g8.5g4.1g2.2g0g0.1g15g0.7g21g2.8g0.4g4.8g29g3.1g4.5g0.4g1.7g7.4g9g2g1.9g0.2g3.7g100g100g57g0.4g7.3g20g7.6g100g0.7g9.8g0.1g1.1g14g26g6g0.2g4.8g15g1.2g3.2g1.7g1.2g0.2g0.4g1.2g9.5g4.6g6.3g68g8.5g9.8g0.3g2g18g3.8g13g20g0.2g1.6g1.5g3.8g0.1g0g2.6g5.1g9.2g26g7.4g8g23g0.3g1.9g3.8g16g4.9g19g30g31g0.1g3.2g28g2.8g25g0.1g9.3g0.5g0.1g0.3g1.6g0.4g0.5g0g10g0g0.1g2.5g17g15g11g17g1.1g6.5g0.3g20g3.4g1.2g3.5g13g11g1.7g4.7g58g1g8.5g9.6g0.1g1g0.7g0.3g0.6g13g11g5.8g4.6g0.8g0.2g1g11g7.5g18g15g0g6.6g18g13g8g1.1g5.9g9.8g0g18g4g4.8g4g18g14g6.4g14g0.3g23g9.5g18g1.7g0.4g0.4g2g0g1.4g26g4.1g1.2g1.7g10g4.1g19g51g4.8g1.2g1.4g27g8.8g6g2.4g36g31g8.8g1.3g4.4g10g0g0.1g1.5g56g3.5g12g13g6.7g4.9g4g4.5g0.1g0.1g16g0.2g0.1g11g0.2g0.2g3g17g36g0.7g17g18g0.2g2.3g4.8g12g100g0.5g15g9.2g20g1g2.7g2.8g2.2g4.8g1.2g3.1g0.1g26g13g0.2g12g0.7g53g8.2g3.6g28g20g0.1g0.2g4.1g0g8.4g28g1.7g1.7g13g10g94g0.2g0.8g5.8g5.3g9.5g0g18g2.8g1.9g11g0.8g0.1g8.4g11g0.8g80g4.8g16g1.9g61g20g2g3.5g2.6g25g0g100g17g0.2g3.5g11g0.5g9.8g1.1g23g18g0g1g1.5g4.5g2.4g1.2g0.4g15g2.3g8.3g0.8g3.6g1.4g0g0.2g25g0.4g6.5g0.4g1.6g21g11g26g17g1.6g19g3.1g0.1g0.2g10g3g0.7g0.9g1.4g1.5g8.5g0g1.5g1.5g0.1g5.1g4.8g16g24g4.2g3.7g0.4g0.8g0.1g3.8g0.3g0.5g16g0g13g5.9g5.7g25g2.9g9g3.1g1g0.7g16g100g8g2.3g0.3g24g25g21g27g21g0.4g5.8g19g0g0.1g66g5.8g27g8.8g16g3.3g0.7g0.4g0.3g81g4g7.3g1.7g11g7.9g30g5g50g51g2.7g0.1g3.4g1.9g0.4g31g41g0.4g0.5g1.5g0.5g0.2g0g5g2.7g15g20g6.5g10g2.7g0g9.3g0.6g0.4g1.4g5.4g0.5g1.1g2g21g9.4g22g0.5g6.3g0g13g8g15g11g9g1.8g5.7g2.6g0.8g52g0.1g0.5g16g14g0.1g0.1g2g0.2g0.2g0.1g0.2g0.1g0.6g2.6g24g0.2g5.6g0.1g0g5.7g0.1g1.7g6.2g8g0.2g3.1g6.3g0.6g5.6g12g2.2g13g0.3g4.7g1.4g7.7g6.7g22g5.1g4.9g18g0.4g9.3g1.6g10g2.4g4g25g24g6.8g0.6g14g0.1g9.9g7.7g0.1g4.3g0.1g0.8g11g17g6.4g5.7g30g0.9g10g12g13g0.5g0.3g0.7g25g0.6g7.6g0g0.4g3.9g0.5g0.3g12g0.1g31g0.1g3.1g0g17g1.7g11g23g24g3.2g33g0.4g0.5g5.5g17g32g4.8g7.1g22g5.8g0.4g0.6g17g3.4g19g17g0.1g0.5g0.4g1.4g11g29g1.6g0.1g1.7g4.4g3.5g15g5.7g9.2g6.3g15g0.2g19g0g10g17g7.6g3.7g2.7g0g15g17g4.2g1.1g10g13g3.3g2.4g6.3g3g11g28g15g0g4.5g2.1g11g100g19g0.1g24g3.7g0.2g1.8g4.1g0g0g9.1g0g4.5g5.1g0.3g4.3g13g4.1g0.8g1.4g0.2g5.4g2.2g11g4.7g4.6g1g9.7g0.5g3.9g28g0.2g0.8g0.4g0g1.1g1.5g1.3g0.2g3.3g1.2g0g0g8.3g0g0g0.1g44g43g15g4.4g15g27g7.8g57g28g5.7g6.4g1g1g0.3g1.2g0.2g2.2g0g0.7g24g0.1g13g0.7g62g2.1g10g5.7g0.2g4.8g1.8g80g12g2.1g1.1g33g9.1g0.3g2.8g0.5g0.6g0.2g0.8g0g0g5.4g10g0.1g1.9g24g0.5g0.1g0.1g2.1g5.8g2g0.5g0.4g1.6g16g34g0.4g0.3g4.5g4.3g1.1g11g0g18g4.7g5.5g76g6g0.6g21g46g22g5.9g12g5.6g1.7g1.8g81g8.1g35g0.8g3.4g0.4g3g3.2g10g5.5g4.7g1.3g6.4g0.9g0.8g0.5g1.4g1.4g6.5g17g13g16g18g8.5g7g9.7g5.4g1.3g3.5g2.3g3.2g3.1g11g5.5g2.8g2.6g0.5g22g0.1g22g4.5g0g9.9g0.7g7.6g11g3.5g5.9g0.1g25g13g48g5.7g5.9g30g1.1g11g0.2g12g5.3g12g12g0.3g7.1g0.7g4.6g0.1g0g0.4g3.7g54g54g4.2g34g2.1g1g9.8g6.1g2.1g6.2g31g2g3.3g7.3g15g3.1g3.2g1.2g3g2.3g5.8g5.7g4.8g2.1g22g29g9.5g13g2g0.4g3.5g16g38g0.4g12g11g8.4g11g3.6g56g1.4g19g1.8g2.9g68g3.5g0.4g2.2g3.5g5.6g7g1.8g0g30g29g4.3g3.7g8g27g3.4g3.3g8.9g10g13g3.2g3.6g7.9g2.4g0.8g0.4g1.5g0.4g17g9.8g6.2g4.4g28g26g31g3.9g60g0.2g9.4g2g0g0.8g37g0.1g0.4g27g9.7g0.3g2.1g13g15g15g5.9g0.5g0.2g2.6g9.9g11g0.6g8.2g8.2g3.9g7.7g0g0g18g11g100g13g25g0.7g0.6g1.2g13g0.1g0.8g4.1g1.3g7.6g0.8g0.1g11g1.2g2.6g17g8.7g4.7g6.3g0.5g22g1.4g3.7g3.5g3.3g0.5g20g10g9.8g3g7.1g5.2g0.1g8.2g8.1g7.1g14g0.5g50g9.1g9.6g9.8g1.9g0.2g1.9g12g3.5g3.6g26g0.7g14g16g0.2g61g10g3g23g10g18g2.2g2.4g2.9g0.8g0.6g4.5g0.5g8.2g10g2.2g80g0.1g0.2g0g13g5g4g0.4g32g7.2g0.1g0.2g0.1g0.7g4.8g29g0.2g12g0.1g4.5g2.6g0g4.1g52g16g13g8.2g1.9g12g15g0.2g4.7g1.7g1.6g20g4.1g9.8g6.5g1.2g11g17g3.6g5.7g1g0.1g17g3.4g10g0.1g0.3g19g6.1g5g11g0.6g0.6g3.5g

In [ ]:
nutrition.total_fat.max()

'9g'

In [ ]:
nutrition.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
Index: 8789 entries, Cornstarch to Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round steak, round
Columns: 75 entries, serving_size to water
dtypes: int64(2), object(73)
memory usage: 5.3+ MB

# The astype() Method

In [ ]:
df = pd.DataFrame({
    'age': [12, 13, 14, 16],
    'weigth': [41.1, 34.5, 83.2, 90.1],
    'height': ['1.72', '1.74', '1.91', '1.54']
})

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     4 non-null      int64
 1   weigth  4 non-null      float64
 2   height  4 non-null      object
dtypes: float64(1), int64(1), object(1)
memory usage: 224.0+ bytes

In [ ]:
df

   age  weigth height
0   12    41.1   1.72
1   13    34.5   1.74
2   14    83.2   1.91
3   16    90.1   1.54

In [ ]:
# Converts all columns to same datatype
df.astype(float)
# Returns a copy of the modified dataframe
# Does not have inplace parameter
# To modify oroiginal dataframe: df = df.astype(float)

    age  weigth  height
0  12.0    41.1    1.72
1  13.0    34.5    1.74
2  14.0    83.2    1.91
3  16.0    90.1    1.54

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     4 non-null      int64
 1   weigth  4 non-null      float64
 2   height  4 non-null      object
dtypes: float64(1), int64(1), object(1)
memory usage: 224.0+ bytes

In [ ]:
# Converts a subset of columns to differemt datatypes
df.astype({'age': int})

   age  weigth height
0   12    41.1   1.72
1   13    34.5   1.74
2   14    83.2   1.91
3   16    90.1   1.54

In [ ]:
# Supports: Python datatypes and numpy dtypes
df.astype({'age': np.int16})
# np.int16 --> numpy 16 bit integer

   age  weigth height
0   12    41.1   1.72
1   13    34.5   1.74
2   14    83.2   1.91
3   16    90.1   1.54

In [ ]:
# nutrition.iloc[:4, :].astype(float)
# Returns value error

In [ ]:
float(714)

714.0

In [ ]:
float('714')

714.0

In [ ]:
# float('714g')
# ValueError: could not convert string to float: '714g'

# DataFrame replace() + A Glimpse at Regex

In [ ]:
dfm = nutrition.iloc[:6, :1]

In [ ]:
dfm.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Cornstarch to Cauliflower, raw
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   serving_size  6 non-null      object
dtypes: object(1)
memory usage: 96.0+ bytes

In [ ]:
dfm

                 serving_size
name
Cornstarch              100 g
Nuts, pecans            100 g
Eggplant, raw           100 g
Teff, uncooked          100 g
Sherbet, orange         100 g
Cauliflower, raw        100 g

In [ ]:
dfm.replace(to_replace='100 g', value = 100)
# to_replace and value are 1st and 2nd positional parameters respectively.
# Hence, we can also use function as: dfm.replace('100 g', 100)

                  serving_size
name
Cornstarch                 100
Nuts, pecans               100
Eggplant, raw              100
Teff, uncooked             100
Sherbet, orange            100
Cauliflower, raw           100

In [ ]:
dfm.replace(to_replace='100 g', value = 100).info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Cornstarch to Cauliflower, raw
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   serving_size  6 non-null      int64
dtypes: int64(1)
memory usage: 96.0+ bytes

In [ ]:
# replace() only looks for exact value to replace else does nothing
dfm.replace('g', '')

                 serving_size
name
Cornstarch              100 g
Nuts, pecans            100 g
Eggplant, raw           100 g
Teff, uncooked          100 g
Sherbet, orange         100 g
Cauliflower, raw        100 g

In [ ]:
# replace() has regex parameters which can be used to replace test patterns.
# By default it is set stp False: regex=False
dfm.replace('\sg', '', regex=True)

                 serving_size
name
Cornstarch                100
Nuts, pecans              100
Eggplant, raw             100
Teff, uncooked            100
Sherbet, orange           100
Cauliflower, raw          100

In [ ]:
dfm.replace('\sg', '', regex=True).info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Cornstarch to Cauliflower, raw
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   serving_size  6 non-null      object
dtypes: object(1)
memory usage: 96.0+ bytes

In [ ]:
dfm.replace('\sg', '', regex=True).astype(int)

                  serving_size
name
Cornstarch                 100
Nuts, pecans               100
Eggplant, raw              100
Teff, uncooked             100
Sherbet, orange            100
Cauliflower, raw           100

In [ ]:
dfm.replace('\sg', '', regex=True).astype(int).info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Cornstarch to Cauliflower, raw
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   serving_size  6 non-null      int64
dtypes: int64(1)
memory usage: 96.0+ bytes

# Part I: Collecting The Units
* Extract units from each column

In [ ]:
nutrition.replace('[^a-zA-Z]', '', regex=True).head()
# Notice calories column is untouched as it is numeric and regex being string manipulation , did not replace it at all.

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
Cornstarch,g,381,g,NaN,,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
"Nuts, pecans",g,691,g,g,,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
"Eggplant, raw",g,25,g,NaN,,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
"Teff, uncooked",g,367,g,g,,mg,mg,,,mg,...,g,g,g,g,,,g,,,g
"Sherbet, orange",g,144,g,g,mg,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g

In [ ]:
# We first typecasted all columns to string type and then carried out replacement. Now calories will also be replaced
nutrition.astype(str).replace('[^a-zA-Z]', '', regex=True).head()

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
Cornstarch,g,,g,nan,,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
"Nuts, pecans",g,,g,g,,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
"Eggplant, raw",g,,g,nan,,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
"Teff, uncooked",g,,g,g,,mg,mg,,,mg,...,g,g,g,g,,,g,,,g
"Sherbet, orange",g,,g,g,mg,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g

In [ ]:
units = nutrition.astype(str).replace('[^a-zA-Z]', '', regex=True)
units.head()

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
Cornstarch,g,,g,nan,,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
"Nuts, pecans",g,,g,g,,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
"Eggplant, raw",g,,g,nan,,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
"Teff, uncooked",g,,g,g,,mg,mg,,,mg,...,g,g,g,g,,,g,,,g
"Sherbet, orange",g,,g,g,mg,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g

In [ ]:
units.saturated_fat

name
Cornstarch                                                                                            nan
Nuts, pecans                                                                                            g
Eggplant, raw                                                                                         nan
Teff, uncooked                                                                                          g
Sherbet, orange                                                                                         g
                                                                                                     ...
Beef, raw, all grades, trimmed to 0" fat, separable lean and fat, boneless, top round roast, round      g
Lamb, cooked, separable lean only, composite of trimmed retail cuts, frozen, imported, New Zealand      g
Lamb, raw, separable lean and fat, composite of trimmed retail cuts, frozen, imported, New Zealand      g
Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round roast, round      g
Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round steak, round      g
Name: saturated_fat, Length: 8789, dtype: object

In [ ]:
units.saturated_fat.value_counts()

g      7199
nan    1590
Name: saturated_fat, dtype: int64

In [ ]:
units.saturated_fat.mode()
# when we apply mode to a series, we get a series in return

0    g
dtype: object

In [ ]:
units.mode()
# when we apply mode to a dataframe, we get a dataframe in return

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,g,,g,g,mg,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g

In [ ]:
units = units.mode()

In [ ]:
units

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,g,,g,g,mg,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g

# The rename() Method
* index={key:value} --> to modify index labels
* columns={key:value} --> to modify column labels
* Only returns a copy. Does not alter the undelying dataframe
* Default: inplace=False

In [ ]:
df

   age  weigth height
0   12    41.1   1.72
1   13    34.5   1.74
2   14    83.2   1.91
3   16    90.1   1.54

In [ ]:
df.rename(index={0:'Pikachu'})

         age  weigth height
Pikachu   12    41.1   1.72
1         13    34.5   1.74
2         14    83.2   1.91
3         16    90.1   1.54

In [ ]:
df.rename(index={0:'Pikachu', 1:'Andy'})

         age  weigth height
Pikachu   12    41.1   1.72
Andy      13    34.5   1.74
2         14    83.2   1.91
3         16    90.1   1.54

In [ ]:
df.rename(columns={'weigth':'Weigth (Kg)'})

   age  Weigth (Kg) height
0   12         41.1   1.72
1   13         34.5   1.74
2   14         83.2   1.91
3   16         90.1   1.54

In [ ]:
df.rename(columns={'weigth':'Weigth (Kg)'}, index={0:'Pikachu'})

         age  Weigth (Kg) height
Pikachu   12         41.1   1.72
1         13         34.5   1.74
2         14         83.2   1.91
3         16         90.1   1.54

mapper parameter
* pass dictionary of old and new label mapping
* has default axis=0 parameters
* can only modify index or column label at a time, not both at the same time

In [ ]:
df.rename(mapper={'height':'Height (m)'})
# df.rename(mapper={'height':'Height (m)'}, axis=0) ~ df.rename(mapper={'height':'Height (m)'})

   age  weigth height
0   12    41.1   1.72
1   13    34.5   1.74
2   14    83.2   1.91
3   16    90.1   1.54

In [ ]:
df.rename(mapper={'height':'Height (m)'}, axis=1)

   age  weigth Height (m)
0   12    41.1       1.72
1   13    34.5       1.74
2   14    83.2       1.91
3   16    90.1       1.54

In [ ]:
df.rename(mapper={'height':'Height (m)'}, axis='columns')

   age  weigth Height (m)
0   12    41.1       1.72
1   13    34.5       1.74
2   14    83.2       1.91
3   16    90.1       1.54

# DataFrame dropna()
* Also supports inplace parameter: default is inplace=False

In [ ]:
df

   age  weigth height
0   12    41.1   1.72
1   13    34.5   1.74
2   14    83.2   1.91
3   16    90.1   1.54

In [ ]:
df.loc[2, 'weigth'] = np.nan

In [ ]:
df.loc[1, :] = np.nan

In [ ]:
df

    age  weigth height
0  12.0    41.1   1.72
1   NaN     NaN    NaN
2  14.0     NaN   1.91
3  16.0    90.1   1.54

In [ ]:
# Using dropna() without parameters
df.dropna()
# Notice it drops row 1 and 2 as they had null values
# This is because of two parameters:
# * how='any' --> meaning drop sequence of values in entirety if any oen vakue is NaN
# * axis=0 ---> meaning dropna actioned across rows

    age  weigth height
0  12.0    41.1   1.72
3  16.0    90.1   1.54

In [ ]:
# df.dropna() ~ df.dropna(how='any', axis=0)
df.dropna(how='any', axis=0)

    age  weigth height
0  12.0    41.1   1.72
3  16.0    90.1   1.54

In [ ]:
df.dropna(how='all', axis=0)
# how='all' --> meaning drop sequence of value sin entirety if all values atre NaN

    age  weigth height
0  12.0    41.1   1.72
2  14.0     NaN   1.91
3  16.0    90.1   1.54

thresh paramater:
* Short of threshold
* Allows us to specify how many non-NaNs a sequence of values can have

In [ ]:
df.dropna(thresh=3, axis=0)
# Notice: it is setting threshold for Non-NaNs to maximum (i.e. total number of columns)
# Notice: it is equivalent in outcome to how='any'

    age  weigth height
0  12.0    41.1   1.72
3  16.0    90.1   1.54

In [ ]:
# Just generalising maximum threshold syntax
df.dropna(thresh=df.shape[1], axis=0)

    age  weigth height
0  12.0    41.1   1.72
3  16.0    90.1   1.54

In [ ]:
df.dropna(axis=1)
# Notice: default how='any' --> meaning any oen Null value in a sequence of value, that complete sequence will be dropped
# Also, we specified axis=1, meaning this function actioned across columns

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [ ]:
df.dropna(how='all', axis=1)

    age  weigth height
0  12.0    41.1   1.72
1   NaN     NaN    NaN
2  14.0     NaN   1.91
3  16.0    90.1   1.54

In [ ]:
df.dropna(thresh=3, axis=1)

    age height
0  12.0   1.72
1   NaN    NaN
2  14.0   1.91
3  16.0   1.54

# Bonus- dropna() With Subset
* subset takes list of orthogonal labels only

In [ ]:
df

    age  weigth height
0  12.0    41.1   1.72
1   NaN     NaN    NaN
2  14.0     NaN   1.91
3  16.0    90.1   1.54

In [ ]:
df['gender'] = ['M', 'F', np.nan, 'M']

In [ ]:
df

    age  weigth height gender
0  12.0    41.1   1.72      M
1   NaN     NaN    NaN      F
2  14.0     NaN   1.91    NaN
3  16.0    90.1   1.54      M

In [ ]:
# dropna() with subset restricts teh application of method at only the subset specified
df.dropna(axis=0, how='any', subset=['gender'])

    age  weigth height gender
0  12.0    41.1   1.72      M
1   NaN     NaN    NaN      F
3  16.0    90.1   1.54      M

In [ ]:
df.dropna(axis=1, how='any', subset=[0,2])

    age height
0  12.0   1.72
1   NaN    NaN
2  14.0   1.91
3  16.0   1.54

# Part II: Merging Units With Column Names

In [ ]:
units

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,g,,g,g,mg,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g

DataFrame Iteration:

In [ ]:
for k in units:
  print(k)

serving_size
calories
total_fat
saturated_fat
cholesterol
sodium
choline
folate
folic_acid
niacin
pantothenic_acid
riboflavin
thiamin
vitamin_a
vitamin_a_rae
carotene_alpha
carotene_beta
cryptoxanthin_beta
lutein_zeaxanthin
lucopene
vitamin_b12
vitamin_b6
vitamin_c
vitamin_d
vitamin_e
tocopherol_alpha
vitamin_k
calcium
copper
irom
magnesium
manganese
phosphorous
potassium
selenium
zink
protein
alanine
arginine
aspartic_acid
cystine
glutamic_acid
glycine
histidine
hydroxyproline
isoleucine
leucine
lysine
methionine
phenylalanine
proline
serine
threonine
tryptophan
tyrosine
valine
carbohydrate
fiber
sugars
fructose
galactose
glucose
lactose
maltose
sucrose
fat
saturated_fatty_acids
monounsaturated_fatty_acids
polyunsaturated_fatty_acids
fatty_acids_total_trans
alcohol
ash
caffeine
theobromine
water

In [ ]:
for k in units:
  print(k, units[k])

serving_size 0    g
Name: serving_size, dtype: object
calories 0
Name: calories, dtype: object
total_fat 0    g
Name: total_fat, dtype: object
saturated_fat 0    g
Name: saturated_fat, dtype: object
cholesterol 0    mg
Name: cholesterol, dtype: object
sodium 0    mg
Name: sodium, dtype: object
choline 0    mg
Name: choline, dtype: object
folate 0    mcg
Name: folate, dtype: object
folic_acid 0    mcg
Name: folic_acid, dtype: object
niacin 0    mg
Name: niacin, dtype: object
pantothenic_acid 0    mg
Name: pantothenic_acid, dtype: object
riboflavin 0    mg
Name: riboflavin, dtype: object
thiamin 0    mg
Name: thiamin, dtype: object
vitamin_a 0    IU
Name: vitamin_a, dtype: object
vitamin_a_rae 0    mcg
Name: vitamin_a_rae, dtype: object
carotene_alpha 0    mcg
Name: carotene_alpha, dtype: object
carotene_beta 0    mcg
Name: carotene_beta, dtype: object
cryptoxanthin_beta 0    mcg
Name: cryptoxanthin_beta, dtype: object
lutein_zeaxanthin 0    mcg
Name: lutein_zeaxanthin, dtype: object
lucopene 0
Name: lucopene, dtype: object
vitamin_b12 0    mcg
Name: vitamin_b12, dtype: object
vitamin_b6 0    mg
Name: vitamin_b6, dtype: object
vitamin_c 0    mg
Name: vitamin_c, dtype: object
vitamin_d 0    IU
Name: vitamin_d, dtype: object
vitamin_e 0    mg
Name: vitamin_e, dtype: object
tocopherol_alpha 0    mg
Name: tocopherol_alpha, dtype: object
vitamin_k 0    mcg
Name: vitamin_k, dtype: object
calcium 0    mg
Name: calcium, dtype: object
copper 0    mg
Name: copper, dtype: object
irom 0    mg
Name: irom, dtype: object
magnesium 0    mg
Name: magnesium, dtype: object
manganese 0    mg
Name: manganese, dtype: object
phosphorous 0    mg
Name: phosphorous, dtype: object
potassium 0    mg
Name: potassium, dtype: object
selenium 0    mcg
Name: selenium, dtype: object
zink 0    mg
Name: zink, dtype: object
protein 0    g
Name: protein, dtype: object
alanine 0    g
Name: alanine, dtype: object
arginine 0    g
Name: arginine, dtype: object
aspartic_acid 0    g
Name: aspartic_acid, dtype: object
cystine 0    g
Name: cystine, dtype: object
glutamic_acid 0    g
Name: glutamic_acid, dtype: object
glycine 0    g
Name: glycine, dtype: object
histidine 0    g
Name: histidine, dtype: object
hydroxyproline 0
Name: hydroxyproline, dtype: object
isoleucine 0    g
Name: isoleucine, dtype: object
leucine 0    g
Name: leucine, dtype: object
lysine 0    g
Name: lysine, dtype: object
methionine 0    g
Name: methionine, dtype: object
phenylalanine 0    g
Name: phenylalanine, dtype: object
proline 0    g
Name: proline, dtype: object
serine 0    g
Name: serine, dtype: object
threonine 0    g
Name: threonine, dtype: object
tryptophan 0    g
Name: tryptophan, dtype: object
tyrosine 0    g
Name: tyrosine, dtype: object
valine 0    g
Name: valine, dtype: object
carbohydrate 0    g
Name: carbohydrate, dtype: object
fiber 0    g
Name: fiber, dtype: object
sugars 0    g
Name: sugars, dtype: object
fructose 0
Name: fructose, dtype: object
galactose 0
Name: galactose, dtype: object
glucose 0
Name: glucose, dtype: object
lactose 0
Name: lactose, dtype: object
maltose 0
Name: maltose, dtype: object
sucrose 0
Name: sucrose, dtype: object
fat 0    g
Name: fat, dtype: object
saturated_fatty_acids 0    g
Name: saturated_fatty_acids, dtype: object
monounsaturated_fatty_acids 0    g
Name: monounsaturated_fatty_acids, dtype: object
polyunsaturated_fatty_acids 0    g
Name: polyunsaturated_fatty_acids, dtype: object
fatty_acids_total_trans 0    mg
Name: fatty_acids_total_trans, dtype: object
alcohol 0    g
Name: alcohol, dtype: object
ash 0    g
Name: ash, dtype: object
caffeine 0    mg
Name: caffeine, dtype: object
theobromine 0    mg
Name: theobromine, dtype: object
water 0    g
Name: water, dtype: object

In [ ]:
for k in units:
  print(k, units[k].at[0])

serving_size g
calories
total_fat g
saturated_fat g
cholesterol mg
sodium mg
choline mg
folate mcg
folic_acid mcg
niacin mg
pantothenic_acid mg
riboflavin mg
thiamin mg
vitamin_a IU
vitamin_a_rae mcg
carotene_alpha mcg
carotene_beta mcg
cryptoxanthin_beta mcg
lutein_zeaxanthin mcg
lucopene
vitamin_b12 mcg
vitamin_b6 mg
vitamin_c mg
vitamin_d IU
vitamin_e mg
tocopherol_alpha mg
vitamin_k mcg
calcium mg
copper mg
irom mg
magnesium mg
manganese mg
phosphorous mg
potassium mg
selenium mcg
zink mg
protein g
alanine g
arginine g
aspartic_acid g
cystine g
glutamic_acid g
glycine g
histidine g
hydroxyproline
isoleucine g
leucine g
lysine g
methionine g
phenylalanine g
proline g
serine g
threonine g
tryptophan g
tyrosine g
valine g
carbohydrate g
fiber g
sugars g
fructose
galactose
glucose
lactose
maltose
sucrose
fat g
saturated_fatty_acids g
monounsaturated_fatty_acids g
polyunsaturated_fatty_acids g
fatty_acids_total_trans mg
alcohol g
ash g
caffeine mg
theobromine mg
water g

In [ ]:
units = units.replace('', np.nan).dropna(axis=1)

In [ ]:
for k in units:
  print(units[k].at[0])

g
g
g
mg
mg
mg
mcg
mcg
mg
mg
mg
mg
IU
mcg
mcg
mcg
mcg
mcg
mcg
mg
mg
IU
mg
mg
mcg
mg
mg
mg
mg
mg
mg
mg
mcg
mg
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
g
mg
g
g
mg
mg
g

In [ ]:
mapper = {k:k+'_'+units[k].at[0] for k in units}

In [ ]:
mapper

{'serving_size': 'serving_size_g',
 'total_fat': 'total_fat_g',
 'saturated_fat': 'saturated_fat_g',
 'cholesterol': 'cholesterol_mg',
 'sodium': 'sodium_mg',
 'choline': 'choline_mg',
 'folate': 'folate_mcg',
 'folic_acid': 'folic_acid_mcg',
 'niacin': 'niacin_mg',
 'pantothenic_acid': 'pantothenic_acid_mg',
 'riboflavin': 'riboflavin_mg',
 'thiamin': 'thiamin_mg',
 'vitamin_a': 'vitamin_a_IU',
 'vitamin_a_rae': 'vitamin_a_rae_mcg',
 'carotene_alpha': 'carotene_alpha_mcg',
 'carotene_beta': 'carotene_beta_mcg',
 'cryptoxanthin_beta': 'cryptoxanthin_beta_mcg',
 'lutein_zeaxanthin': 'lutein_zeaxanthin_mcg',
 'vitamin_b12': 'vitamin_b12_mcg',
 'vitamin_b6': 'vitamin_b6_mg',
 'vitamin_c': 'vitamin_c_mg',
 'vitamin_d': 'vitamin_d_IU',
 'vitamin_e': 'vitamin_e_mg',
 'tocopherol_alpha': 'tocopherol_alpha_mg',
 'vitamin_k': 'vitamin_k_mcg',
 'calcium': 'calcium_mg',
 'copper': 'copper_mg',
 'irom': 'irom_mg',
 'magnesium': 'magnesium_mg',
 'manganese': 'manganese_mg',
 'phosphorous': 'phosphorous_mg',
 'potassium': 'potassium_mg',
 'selenium': 'selenium_mcg',
 'zink': 'zink_mg',
 'protein': 'protein_g',
 'alanine': 'alanine_g',
 'arginine': 'arginine_g',
 'aspartic_acid': 'aspartic_acid_g',
 'cystine': 'cystine_g',
 'glutamic_acid': 'glutamic_acid_g',
 'glycine': 'glycine_g',
 'histidine': 'histidine_g',
 'isoleucine': 'isoleucine_g',
 'leucine': 'leucine_g',
 'lysine': 'lysine_g',
 'methionine': 'methionine_g',
 'phenylalanine': 'phenylalanine_g',
 'proline': 'proline_g',
 'serine': 'serine_g',
 'threonine': 'threonine_g',
 'tryptophan': 'tryptophan_g',
 'tyrosine': 'tyrosine_g',
 'valine': 'valine_g',
 'carbohydrate': 'carbohydrate_g',
 'fiber': 'fiber_g',
 'sugars': 'sugars_g',
 'fat': 'fat_g',
 'saturated_fatty_acids': 'saturated_fatty_acids_g',
 'monounsaturated_fatty_acids': 'monounsaturated_fatty_acids_g',
 'polyunsaturated_fatty_acids': 'polyunsaturated_fatty_acids_g',
 'fatty_acids_total_trans': 'fatty_acids_total_trans_mg',
 'alcohol': 'alcohol_g',
 'ash': 'ash_g',
 'caffeine': 'caffeine_mg',
 'theobromine': 'theobromine_mg',
 'water': 'water_g'}

In [ ]:
nutrition.rename(columns=mapper).head()

,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,niacin_mg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
name,,,,,,,,,,,,,,,,,,,,,
Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,0.000 mg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,1.167 mg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,0.649 mg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,3.363 mg,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,0.063 mg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

In [ ]:
nutrition.rename(columns=mapper, inplace=True)

In [ ]:
nutrition.head()

,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,niacin_mg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
name,,,,,,,,,,,,,,,,,,,,,
Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,0.000 mg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,1.167 mg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,0.649 mg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,3.363 mg,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,0.063 mg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

# Part III: Removings Units From Values

In [ ]:
nutrition.head()

,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,niacin_mg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
name,,,,,,,,,,,,,,,,,,,,,
Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,0.000 mg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,1.167 mg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,0.649 mg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,3.363 mg,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,0.063 mg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

In [ ]:
# Replacing units from dataframe values:
nutrition.replace('[a-zA-Z]', '', regex=True, inplace=True)

In [ ]:
nutrition.head()

,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,niacin_mg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
name,,,,,,,,,,,,,,,,,,,,,
Cornstarch,100,381,0.1,NaN,0,9.00,0.4,0.00,0.00,0.000,...,0.05,0.009,0.016,0.025,0.00,0.0,0.09,0.00,0.00,8.32
"Nuts, pecans",100,691,72,6.2,0,0.00,40.5,22.00,0.00,1.167,...,71.97,6.180,40.801,21.614,0.00,0.0,1.49,0.00,0.00,3.52
"Eggplant, raw",100,25,0.2,NaN,0,2.00,6.9,22.00,0.00,0.649,...,0.18,0.034,0.016,0.076,0.00,0.0,0.66,0.00,0.00,92.30
"Teff, uncooked",100,367,2.4,0.4,0,12.00,13.1,0,0,3.363,...,2.38,0.449,0.589,1.071,0,0,2.37,0,0,8.82
"Sherbet, orange",100,144,2,1.2,1,46.00,7.7,4.00,0.00,0.063,...,2.00,1.160,0.530,0.080,1.00,0.0,0.40,0.00,0.00,66.10

In [ ]:
nutrition.dtypes

serving_size_g     object
calories            int64
total_fat_g        object
saturated_fat_g    object
cholesterol_mg     object
                    ...
alcohol_g          object
ash_g              object
caffeine_mg        object
theobromine_mg     object
water_g            object
Length: 75, dtype: object

In [ ]:
nutrition.dtypes.value_counts()

object    73
int64      2
dtype: int64

In [ ]:
# Type cast our values to float and re-assign to nutritions dataframe
nutrition = nutrition.astype(float)

In [ ]:
nutrition.dtypes.value_counts()

float64    75
dtype: int64

In [ ]:
# Now we can do arithmatic operations like:
nutrition.total_fat_g.sum()

92784.20000000001

# Filtering in 2D
* filter() method
* axis=0/1 for filtering along index/column labels respectively
* like: literal case-sensitive contains condition
* regex: different patterns etc
* items=[]: specify exact list of lables we want
* Can also be used with loc[] indexer to filter labels

In [ ]:
nutrition.head(3)

,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,niacin_mg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
name,,,,,,,,,,,,,,,,,,,,,
Cornstarch,100.0,381.0,0.1,NaN,0.0,9.0,0.4,0.0,0.0,0.000,...,0.05,0.009,0.016,0.025,0.0,0.0,0.09,0.0,0.0,8.32
"Nuts, pecans",100.0,691.0,72.0,6.2,0.0,0.0,40.5,22.0,0.0,1.167,...,71.97,6.180,40.801,21.614,0.0,0.0,1.49,0.0,0.0,3.52
"Eggplant, raw",100.0,25.0,0.2,NaN,0.0,2.0,6.9,22.0,0.0,0.649,...,0.18,0.034,0.016,0.076,0.0,0.0,0.66,0.0,0.0,92.30

In [ ]:
nutrition.filter(axis=0, like='Octopus')

,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,niacin_mg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
name,,,,,,,,,,,,,,,,,,,,,
Octopus (Alaska Native),100.0,56.0,0.8,0.2,41.0,0.0,0.0,0.0,0.0,2.0,...,0.8,0.2,0.0,0.2,41.0,0.0,1.5,0.0,0.0,84.0

In [ ]:
nutrition.filter(axis=0, like='octopus')

,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,niacin_mg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
name,,,,,,,,,,,,,,,,,,,,,
"Mollusks, raw, common, octopus",100.0,82.0,1.0,0.2,48.0,230.0,65.0,16.0,0.0,2.10,...,1.04,0.227,0.162,0.239,48.0,0.0,1.6,0.0,0.0,80.25
"Mollusks, moist heat, cooked, common, octopus",100.0,164.0,2.1,0.5,96.0,460.0,81.0,24.0,0.0,3.78,...,2.08,0.453,0.324,0.477,96.0,0.0,3.2,0.0,0.0,60.50

In [ ]:
nutrition.filter(axis=0, regex='octopus')

,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,niacin_mg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
name,,,,,,,,,,,,,,,,,,,,,
"Mollusks, raw, common, octopus",100.0,82.0,1.0,0.2,48.0,230.0,65.0,16.0,0.0,2.10,...,1.04,0.227,0.162,0.239,48.0,0.0,1.6,0.0,0.0,80.25
"Mollusks, moist heat, cooked, common, octopus",100.0,164.0,2.1,0.5,96.0,460.0,81.0,24.0,0.0,3.78,...,2.08,0.453,0.324,0.477,96.0,0.0,3.2,0.0,0.0,60.50

In [ ]:
nutrition.filter(axis=0, regex='[oO]ctopus')

,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,niacin_mg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
name,,,,,,,,,,,,,,,,,,,,,
Octopus (Alaska Native),100.0,56.0,0.8,0.2,41.0,0.0,0.0,0.0,0.0,2.00,...,0.80,0.200,0.000,0.200,41.0,0.0,1.5,0.0,0.0,84.00
"Mollusks, raw, common, octopus",100.0,82.0,1.0,0.2,48.0,230.0,65.0,16.0,0.0,2.10,...,1.04,0.227,0.162,0.239,48.0,0.0,1.6,0.0,0.0,80.25
"Mollusks, moist heat, cooked, common, octopus",100.0,164.0,2.1,0.5,96.0,460.0,81.0,24.0,0.0,3.78,...,2.08,0.453,0.324,0.477,96.0,0.0,3.2,0.0,0.0,60.50

In [ ]:
nutrition.filter(axis=0, regex='(?i)octopus')

,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,niacin_mg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
name,,,,,,,,,,,,,,,,,,,,,
Octopus (Alaska Native),100.0,56.0,0.8,0.2,41.0,0.0,0.0,0.0,0.0,2.00,...,0.80,0.200,0.000,0.200,41.0,0.0,1.5,0.0,0.0,84.00
"Mollusks, raw, common, octopus",100.0,82.0,1.0,0.2,48.0,230.0,65.0,16.0,0.0,2.10,...,1.04,0.227,0.162,0.239,48.0,0.0,1.6,0.0,0.0,80.25
"Mollusks, moist heat, cooked, common, octopus",100.0,164.0,2.1,0.5,96.0,460.0,81.0,24.0,0.0,3.78,...,2.08,0.453,0.324,0.477,96.0,0.0,3.2,0.0,0.0,60.50

In [ ]:
# Filtering cholesterol value for octopus
nutrition.filter(axis=0, regex='(?i)octopus')\
.filter(axis=1, items=['cholesterol_mg','serving_size_g','calories'])

,cholesterol_mg,serving_size_g,calories
name,,,
Octopus (Alaska Native),41.0,100.0,56.0
"Mollusks, raw, common, octopus",48.0,100.0,82.0
"Mollusks, moist heat, cooked, common, octopus",96.0,100.0,164.0

In [ ]:
# Filtering cholesterol value for octopus using loc indexer
nutrition.filter(axis=0, regex='(?i)octopus')\
.loc[:,['cholesterol_mg','serving_size_g','calories']]

,cholesterol_mg,serving_size_g,calories
name,,,
Octopus (Alaska Native),41.0,100.0,56.0
"Mollusks, raw, common, octopus",48.0,100.0,82.0
"Mollusks, moist heat, cooked, common, octopus",96.0,100.0,164.0

# DataFrame Sorting

Sorting with series

In [ ]:
nutrition.vitamin_b12_mcg

name
Cornstarch                                                                                            0.00
Nuts, pecans                                                                                          0.00
Eggplant, raw                                                                                         0.00
Teff, uncooked                                                                                        0.00
Sherbet, orange                                                                                       0.13
                                                                                                      ...
Beef, raw, all grades, trimmed to 0" fat, separable lean and fat, boneless, top round roast, round    1.64
Lamb, cooked, separable lean only, composite of trimmed retail cuts, frozen, imported, New Zealand    2.95
Lamb, raw, separable lean and fat, composite of trimmed retail cuts, frozen, imported, New Zealand    2.42
Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round roast, round    1.84
Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round steak, round    1.84
Name: vitamin_b12_mcg, Length: 8789, dtype: float64

In [ ]:
type(nutrition.vitamin_b12_mcg)

pandas.core.series.Series

In [ ]:
nutrition.vitamin_b12_mcg.sort_values()

name
Cornstarch                                                                           0.00
Apricots, stewed, sulfured, dehydrated (low-moisture)                                0.00
Cocoa, processed with alkali, unsweetened, dry powder                                0.00
Tomato products, with herbs and cheese, sauce, canned                                0.00
Mothbeans, without salt, boiled, cooked, mature seeds                                0.00
                                                                                    ...
Veal, braised, cooked, liver, variety meats and by-products                         84.60
Lamb, pan-fried, cooked, liver, variety meats and by-products                       85.70
Lamb, raw, liver, variety meats and by-products                                     90.05
Beef, boiled, cooked, variety meats and by-products liver, imported, New Zealand    96.00
Mollusks, moist heat, cooked, mixed species, clam                                   98.89
Name: vitamin_b12_mcg, Length: 8789, dtype: float64

Sorting dataframes

In [ ]:
# nutrition.sort_values()
# TypeError: sort_values() missing 1 required positional argument: 'by'

In [ ]:
# Sorting by specific column labels:
nutrition.sort_values(by=['calories'], ascending=False).head(3)

,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,niacin_mg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
name,,,,,,,,,,,,,,,,,,,,,
"Fat, mutton tallow",100.0,902.0,100.0,47.0,102.0,0.0,79.8,0.0,0.0,0.0,...,100.0,47.300,40.600,7.800,102.0,0.0,0.0,0.0,0.0,0.0
"Fish oil, salmon",100.0,902.0,100.0,20.0,485.0,0.0,0.0,0.0,0.0,0.0,...,100.0,19.872,29.037,40.324,485.0,0.0,0.0,0.0,0.0,0.0
Lard,100.0,902.0,100.0,39.0,95.0,0.0,49.7,0.0,0.0,0.0,...,100.0,39.200,45.100,11.200,95.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# Sorting by multiple column labels- all in same direction
nutrition.sort_values(by=['cholesterol_mg', 'sodium_mg'], ascending=False).head(3)

,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,niacin_mg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
name,,,,,,,,,,,,,,,,,,,,,
"Veal, braised, cooked, brain, variety meats and by-products",100.0,136.0,9.6,2.2,3100.0,156.0,0.0,3.0,0.0,2.43,...,9.63,2.180,1.740,1.490,3100.0,0.0,1.40,0.0,0.0,76.89
"Beef, simmered, cooked, brain, variety meats and by-products",100.0,151.0,11.0,2.4,3100.0,108.0,490.9,5.0,0.0,3.62,...,10.53,2.394,1.882,1.632,3100.0,0.0,1.46,0.0,0.0,74.86
"Beef, raw, brain, variety meats and by-products",100.0,143.0,10.0,2.3,3010.0,126.0,0.0,3.0,0.0,3.55,...,10.30,2.300,1.890,1.586,3010.0,0.0,1.51,0.0,0.0,76.29

In [ ]:
# Sorting by multiple column labels- but in different direction
nutrition.sort_values(by=['cholesterol_mg', 'sodium_mg'], ascending=[False, True]).head(3)

,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,niacin_mg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
name,,,,,,,,,,,,,,,,,,,,,
"Beef, simmered, cooked, brain, variety meats and by-products",100.0,151.0,11.0,2.4,3100.0,108.0,490.9,5.0,0.0,3.62,...,10.53,2.394,1.882,1.632,3100.0,0.0,1.46,0.0,0.0,74.86
"Veal, braised, cooked, brain, variety meats and by-products",100.0,136.0,9.6,2.2,3100.0,156.0,0.0,3.0,0.0,2.43,...,9.63,2.180,1.740,1.490,3100.0,0.0,1.40,0.0,0.0,76.89
"Beef, raw, brain, variety meats and by-products",100.0,143.0,10.0,2.3,3010.0,126.0,0.0,3.0,0.0,3.55,...,10.30,2.300,1.890,1.586,3010.0,0.0,1.51,0.0,0.0,76.29

In [ ]:
# Brain composition detour
nutrition.loc['Beef, simmered, cooked, brain, variety meats and by-products']\
.filter(like='_g')\
.sort_values(ascending=False)

serving_size_g                   100.000
water_g                           74.860
protein_g                         11.670
total_fat_g                       11.000
fat_g                             10.530
saturated_fat_g                    2.400
saturated_fatty_acids_g            2.394
monounsaturated_fatty_acids_g      1.882
polyunsaturated_fatty_acids_g      1.632
carbohydrate_g                     1.480
ash_g                              1.460
threonine_g                        0.000
alcohol_g                          0.000
sugars_g                           0.000
fiber_g                            0.000
valine_g                           0.000
tyrosine_g                         0.000
tryptophan_g                       0.000
serine_g                           0.000
phenylalanine_g                    0.000
methionine_g                       0.000
lysine_g                           0.000
leucine_g                          0.000
isoleucine_g                       0.000
histidine_g                        0.000
glycine_g                          0.000
glutamic_acid_g                    0.000
cystine_g                          0.000
aspartic_acid_g                    0.000
arginine_g                         0.000
alanine_g                          0.000
proline_g                          0.000
Name: Beef, simmered, cooked, brain, variety meats and by-products, dtype: float64

# Using Series between() With DataFrames
* not directly used with dataframes
* A Boolean-Mask craeted with between() and that boolean-mask used to extract values from dataframe using boolean indexing with []

In [ ]:
# nutrition.between()
# AttributeError: 'DataFrame' object has no attribute 'between'

In [ ]:
# Created a series from dataframe over which between() method will action
nutrition.calories.head(2)

name
Cornstarch      381.0
Nuts, pecans    691.0
Name: calories, dtype: float64

In [ ]:
# creatuing boolean mask from the above fetched series
nutrition.calories.between(20,30)

name
Cornstarch                                                                                            False
Nuts, pecans                                                                                          False
Eggplant, raw                                                                                          True
Teff, uncooked                                                                                        False
Sherbet, orange                                                                                       False
                                                                                                      ...
Beef, raw, all grades, trimmed to 0" fat, separable lean and fat, boneless, top round roast, round    False
Lamb, cooked, separable lean only, composite of trimmed retail cuts, frozen, imported, New Zealand    False
Lamb, raw, separable lean and fat, composite of trimmed retail cuts, frozen, imported, New Zealand    False
Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round roast, round    False
Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round steak, round    False
Name: calories, Length: 8789, dtype: bool

In [ ]:
# Using boolean-mask from above to extract from dataframe using boolean indexing with []
nutrition[nutrition.calories.between(20,30)]

,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,niacin_mg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
name,,,,,,,,,,,,,,,,,,,,,
"Eggplant, raw",100.0,25.0,0.2,NaN,0.0,2.0,6.9,22.0,0.0,0.649,...,0.18,0.034,0.016,0.076,0.0,0.0,0.66,0.0,0.0,92.30
"Cauliflower, raw",100.0,25.0,0.3,0.1,0.0,30.0,44.3,57.0,0.0,0.507,...,0.28,0.130,0.034,0.031,0.0,0.0,0.76,0.0,0.0,92.07
"PACE, Picante Sauce",100.0,25.0,0.0,NaN,0.0,781.0,0.0,0.0,0.0,0.000,...,0.00,0.000,0.000,0.000,0.0,0.0,3.85,0.0,0.0,89.90
"Peppers, raw, jalapeno",100.0,29.0,0.4,0.1,0.0,3.0,7.5,27.0,0.0,1.280,...,0.37,0.092,0.029,0.112,0.0,0.0,0.53,0.0,0.0,91.69
"PACE, Green Taco Sauce",100.0,25.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.000,...,0.00,0.000,0.000,0.000,0.0,0.0,3.05,0.0,0.0,90.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Beverages, with high vitamin C, Fruit flavored drink containing less than 3% fruit juice",100.0,27.0,0.0,NaN,0.0,36.0,0.0,0.0,0.0,0.000,...,0.00,0.000,0.000,0.000,0.0,0.0,0.10,0.0,0.0,93.20
"Squash, with salt, drained, boiled, cooked, frozen, crookneck and straightneck, summer",100.0,25.0,0.2,NaN,0.0,242.0,9.7,13.0,0.0,0.440,...,0.20,0.040,0.015,0.082,0.0,0.0,0.74,0.0,0.0,92.24
"Beverages, prepared with water and ice, powder, with aspartame, reduced calorie, chocolate, dairy drink mix",100.0,29.0,0.2,0.2,2.0,61.0,0.0,3.0,0.0,0.110,...,0.23,0.164,0.043,0.005,2.0,0.0,0.81,2.0,73.0,92.26
"Fruit salad, solids and liquids, water pack, canned, (peach and pear and apricot and pineapple and cherry)",100.0,30.0,0.1,NaN,0.0,3.0,0.0,3.0,0.0,0.374,...,0.07,0.009,0.013,0.028,0.0,0.0,0.22,0.0,0.0,91.50
"Beverages, added calcium, high vitamin C, greater than 3% fruit juice, reduced sugar, Fruit flavored drink",100.0,29.0,0.4,NaN,0.0,25.0,0.1,2.0,0.0,0.000,...,0.37,0.000,0.000,0.000,0.0,0.0,0.06,0.0,0.0,93.00

In [ ]:
nutrition[nutrition.calories.between(20,30)].sample(4)

,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,niacin_mg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
name,,,,,,,,,,,,,,,,,,,,,
"PACE, Diced Green Chilies",100.0,27.0,0.0,NaN,0.0,333.0,0.0,0.0,0.0,0.000,...,0.00,0.000,0.000,0.000,0.0,0.0,1.03,0.0,0.0,92.30
"Lime juice, raw",100.0,25.0,0.1,NaN,0.0,2.0,5.1,10.0,0.0,0.142,...,0.07,0.008,0.008,0.023,0.0,0.0,0.31,0.0,0.0,90.79
"Mustard greens, with salt, drained, boiled, cooked",100.0,26.0,0.5,NaN,0.0,252.0,0.3,9.0,0.0,0.433,...,0.47,0.012,0.110,0.046,0.0,0.0,0.69,0.0,0.0,91.78
"Frozen novelties, no sugar added, fruit, ice type",100.0,24.0,0.1,NaN,0.0,5.0,0.0,0.0,0.0,0.150,...,0.10,0.000,0.000,0.000,0.0,0.0,0.10,0.0,0.0,93.20

# Bonus- Min, Max And Idx[MinMax] And Good Foods

In [ ]:
nutrition.min()
# default is column-wise(axis=0)
# nutrition.min() ~ nutrition.min(axis=0)

serving_size_g     100.0
calories             0.0
total_fat_g          0.0
saturated_fat_g      0.1
cholesterol_mg       0.0
                   ...
alcohol_g            0.0
ash_g                0.0
caffeine_mg          0.0
theobromine_mg       0.0
water_g              0.0
Length: 75, dtype: float64

In [ ]:
nutrition.min(axis=1)

name
Cornstarch                                                                                            0.0
Nuts, pecans                                                                                          0.0
Eggplant, raw                                                                                         0.0
Teff, uncooked                                                                                        0.0
Sherbet, orange                                                                                       0.0
                                                                                                     ...
Beef, raw, all grades, trimmed to 0" fat, separable lean and fat, boneless, top round roast, round    0.0
Lamb, cooked, separable lean only, composite of trimmed retail cuts, frozen, imported, New Zealand    0.0
Lamb, raw, separable lean and fat, composite of trimmed retail cuts, frozen, imported, New Zealand    0.0
Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round roast, round    0.0
Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round steak, round    0.0
Length: 8789, dtype: float64

In [ ]:
nutrition.max(axis=1)

name
Cornstarch                                                                                            381.0
Nuts, pecans                                                                                          691.0
Eggplant, raw                                                                                         229.0
Teff, uncooked                                                                                        429.0
Sherbet, orange                                                                                       144.0
                                                                                                      ...
Beef, raw, all grades, trimmed to 0" fat, separable lean and fat, boneless, top round roast, round    311.0
Lamb, cooked, separable lean only, composite of trimmed retail cuts, frozen, imported, New Zealand    246.0
Lamb, raw, separable lean and fat, composite of trimmed retail cuts, frozen, imported, New Zealand    277.0
Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round roast, round    319.0
Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round steak, round    319.0
Length: 8789, dtype: float64

What food has the most potassium?

In [ ]:
nutrition.potassium_mg.max()

16500.0

In [ ]:
nutrition.potassium_mg.idxmax()

'Leavening agents, cream of tartar'

In [ ]:
nutrition.potassium_mg.sort_values(ascending=False)

name
Leavening agents, cream of tartar                              16500.0
Leavening agents, low-sodium, baking powder                    10100.0
Parsley, freeze-dried                                           6300.0
Beverages, unsweetened, decaffeinated, instant, tea             6040.0
Beverages, powder, unsweetened, instant, tea                    6040.0
                                                                ...
CAMPBELL'S CHUNKY Soups, Beef with White and Wild Rice Soup        0.0
Alcoholic beverage, Pinot Gris (Grigio), white, table, wine        0.0
Cloudberries, raw (Alaska Native)                                  0.0
Oil, all purpose, soy ( partially hydrogenated), industrial        0.0
Oil, sunflower, mid-oleic, industrial                              0.0
Name: potassium_mg, Length: 8789, dtype: float64

Targeting Potassium-to-Sodium == 16

In [ ]:
K_to_NA = (nutrition.potassium_mg.replace(0,1)/nutrition.sodium_mg.replace(0,1))\
.sort_values(ascending=False)

In [ ]:
K_to_NA.head(5)

name
Peanut flour, low fat                                         1358.0
Nuts, raw, pistachio nuts                                     1025.0
Beverages, reduced calorie, with whitener, instant, coffee     909.0
Soybeans, raw, mature seeds                                    898.5
Soy meal, raw, defatted                                        830.0
dtype: float64

In [ ]:
K_to_NA[K_to_NA.between(14,18)].sample(4)

name
Lettuce, raw, iceberg (includes crisphead types)                                                                14.100000
Onions, unprepared, whole, frozen                                                                               14.200000
Fruit cocktail, solids and liquids, heavy syrup, canned, (peach and pineapple and pear and grape and cherry)    14.666667
Kohlrabi, raw                                                                                                   17.500000
dtype: float64

# DataFrame nlargest() And nsmallest()

In [ ]:
nutrition.potassium_mg.sort_values(ascending=False).head(10)

name
Leavening agents, cream of tartar                         16500.0
Leavening agents, low-sodium, baking powder               10100.0
Parsley, freeze-dried                                      6300.0
Beverages, unsweetened, decaffeinated, instant, tea        6040.0
Beverages, powder, unsweetened, instant, tea               6040.0
Spices, dried, chervil                                     4740.0
Spices, dried, coriander leaf                              4466.0
Celery flakes, dried                                       4388.0
Beverages, powder, regular, instant, coffee                3535.0
Beverages, half the caffeine, regular, instant, coffee     3535.0
Name: potassium_mg, dtype: float64

In [ ]:
# Fetching top 10 with nlarget()
# nutrition.nlargest(10)
# TypeError: nlargest() missing 1 required positional argument: 'columns'

In [ ]:
# Only works with column labels
# Pandas need extra label information for which nlarget will be actioned--> done via columns parameter
nutrition.nlargest(n=10, columns='potassium_mg')
# But this returns a dataframe

,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,niacin_mg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
name,,,,,,,,,,,,,,,,,,,,,
"Leavening agents, cream of tartar",100.0,258.0,0.0,NaN,0.0,52.0,0.0,0.0,0.0,0.000,...,0.00,0.000,0.000,0.000,0.0,0.0,36.80,0.0,0.0,1.70
"Leavening agents, low-sodium, baking powder",100.0,97.0,0.4,0.1,0.0,90.0,0.0,0.0,0.0,0.000,...,0.40,0.073,0.006,0.121,0.0,0.0,46.40,0.0,0.0,6.20
"Parsley, freeze-dried",100.0,271.0,5.2,NaN,0.0,391.0,0.0,194.0,0.0,10.400,...,5.20,0.000,0.000,0.000,0.0,0.0,19.12,0.0,0.0,2.00
"Beverages, powder, unsweetened, instant, tea",100.0,315.0,0.0,NaN,0.0,72.0,118.3,103.0,0.0,10.800,...,0.00,0.000,0.000,0.000,0.0,0.0,16.04,5714.0,71.0,5.09
"Beverages, unsweetened, decaffeinated, instant, tea",100.0,315.0,0.0,NaN,0.0,72.0,118.3,103.0,0.0,10.800,...,0.00,0.000,0.000,0.000,0.0,0.0,16.04,169.0,11.0,5.09
"Spices, dried, chervil",100.0,237.0,3.9,0.2,0.0,83.0,0.0,274.0,0.0,5.400,...,3.90,0.169,1.399,1.800,0.0,0.0,16.60,0.0,0.0,7.20
"Spices, dried, coriander leaf",100.0,279.0,4.8,0.1,0.0,211.0,97.1,274.0,0.0,10.707,...,4.78,0.115,2.232,0.328,0.0,0.0,14.08,0.0,0.0,7.30
"Celery flakes, dried",100.0,319.0,2.1,0.6,0.0,1435.0,122.3,107.0,0.0,4.640,...,2.10,0.555,0.405,1.035,0.0,0.0,13.90,0.0,0.0,9.00
"Beverages, powder, regular, instant, coffee",100.0,353.0,0.5,0.2,0.0,37.0,101.9,0.0,0.0,28.173,...,0.50,0.197,0.041,0.196,0.0,0.0,8.80,3142.0,0.0,3.10
"Beverages, half the caffeine, regular, instant, coffee",100.0,352.0,0.5,0.2,0.0,37.0,101.9,0.0,0.0,28.173,...,0.50,0.197,0.041,0.196,0.0,0.0,8.80,1571.0,0.0,3.10

In [ ]:
# Restricting above dataframe to series
nutrition.nlargest(n=10, columns='potassium_mg').potassium_mg

name
Leavening agents, cream of tartar                         16500.0
Leavening agents, low-sodium, baking powder               10100.0
Parsley, freeze-dried                                      6300.0
Beverages, powder, unsweetened, instant, tea               6040.0
Beverages, unsweetened, decaffeinated, instant, tea        6040.0
Spices, dried, chervil                                     4740.0
Spices, dried, coriander leaf                              4466.0
Celery flakes, dried                                       4388.0
Beverages, powder, regular, instant, coffee                3535.0
Beverages, half the caffeine, regular, instant, coffee     3535.0
Name: potassium_mg, dtype: float64

In [ ]:
# Much cleaner approach for above result set:
nutrition.potassium_mg.nlargest(10)

name
Leavening agents, cream of tartar                         16500.0
Leavening agents, low-sodium, baking powder               10100.0
Parsley, freeze-dried                                      6300.0
Beverages, powder, unsweetened, instant, tea               6040.0
Beverages, unsweetened, decaffeinated, instant, tea        6040.0
Spices, dried, chervil                                     4740.0
Spices, dried, coriander leaf                              4466.0
Celery flakes, dried                                       4388.0
Beverages, powder, regular, instant, coffee                3535.0
Beverages, half the caffeine, regular, instant, coffee     3535.0
Name: potassium_mg, dtype: float64

nsmallest()

In [ ]:
nutrition.nsmallest(10, 'sodium_mg')

,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,niacin_mg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
name,,,,,,,,,,,,,,,,,,,,,
"Nuts, pecans",100.0,691.0,72.0,6.2,0.0,0.0,40.5,22.0,0.0,1.167,...,71.97,6.180,40.801,21.614,0.0,0.0,1.49,0.0,0.0,3.52
"PACE, Green Taco Sauce",100.0,25.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.000,...,0.00,0.000,0.000,0.000,0.0,0.0,3.05,0.0,0.0,90.70
"Oil, soybean lecithin",100.0,763.0,100.0,15.0,0.0,0.0,350.0,0.0,0.0,0.000,...,100.00,15.005,10.977,45.318,0.0,0.0,0.00,0.0,0.0,0.00
"Syrup, fruit flavored",100.0,261.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.000,...,0.02,0.000,0.000,0.000,0.0,0.0,0.06,0.0,0.0,34.82
"Oranges, Florida, raw",100.0,46.0,0.2,NaN,0.0,0.0,8.4,17.0,0.0,0.400,...,0.21,0.025,0.039,0.042,0.0,0.0,0.41,0.0,0.0,87.14
"Cherries, raw, sweet",100.0,63.0,0.2,NaN,0.0,0.0,6.1,4.0,0.0,0.154,...,0.20,0.038,0.047,0.052,0.0,0.0,0.48,0.0,0.0,82.25
"Peaches, raw, yellow",100.0,39.0,0.3,NaN,0.0,0.0,6.1,4.0,0.0,0.806,...,0.25,0.019,0.067,0.086,0.0,0.0,0.43,0.0,0.0,88.87
"Oil, corn and canola",100.0,884.0,100.0,8.0,0.0,0.0,0.2,0.0,0.0,0.000,...,100.00,8.026,58.537,29.113,0.0,0.0,0.00,0.0,0.0,0.00
"Game meat, raw, bear",100.0,161.0,8.3,NaN,0.0,0.0,0.0,0.0,0.0,3.200,...,8.30,0.000,0.000,0.000,0.0,0.0,0.70,0.0,0.0,71.20
"Oil, ucuhuba butter",100.0,884.0,100.0,85.0,0.0,0.0,0.0,0.0,0.0,0.000,...,100.00,85.200,6.700,2.900,0.0,0.0,0.00,0.0,0.0,0.00

In [ ]:
# We can also pass multiple columns:
nutrition.nsmallest(10, ['sodium_mg','calories','folate_mcg'])

,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,niacin_mg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
name,,,,,,,,,,,,,,,,,,,,,
"Beverages, well, tap, water",100.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.10,0.0,0.0,99.90
"Water, NAYA, non-carbonated, bottled",100.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.10,0.0,0.0,100.00
"Beverages, decaffeinated, brewed, green, tea",100.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.03,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,99.93
"Beverages, EVIAN, non-carbonated, bottled, water",100.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.05,0.0,0.0,99.97
"Beverages, CALISTOGA, non-carbonated, bottled, water",100.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.10,0.0,0.0,100.00
"Beverages, DANNON, non-carbonated, bottled, water",100.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,99.98
"Sweetener, herbal extract powder from Stevia leaf",100.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00
"Beverages, CRYSTAL GEYSER, non-carbonated, bottled, water",100.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.10,0.0,0.0,100.00
"Babyfood, without added fluoride., GERBER, bottled, water",100.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,99.90
"Beverages, AQUAFINA, PEPSI, non-carbonated, bottled, water",100.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,99.97

# Skill Challenge 1
1. Find the 10 foods that have the most Vitamin_B12. What do they have in common?
2. Isolate the foods in the dataset that contain, or are based on eggplant. Which of them has the most sodium?
3. Select a slice of the dataframe that contains 4 random rows and 2 random columns.

1

In [ ]:
nutrition.vitamin_b12_mcg.nlargest(10)
# nutrition.nlargest(n=10, columns='vitamin_b12_mcg')

name
Mollusks, moist heat, cooked, mixed species, clam                                   98.89
Beef, boiled, cooked, variety meats and by-products liver, imported, New Zealand    96.00
Lamb, raw, liver, variety meats and by-products                                     90.05
Lamb, pan-fried, cooked, liver, variety meats and by-products                       85.70
Veal, braised, cooked, liver, variety meats and by-products                         84.60
Beef, raw, liver, variety meats and by-products, imported, New Zealand              84.50
Beef, pan-fried, cooked, liver, variety meats and by-products                       83.13
Lamb, braised, cooked, kidneys, variety meats and by-products                       78.90
Lamb, braised, cooked, liver, variety meats and by-products                         76.50
Veal, pan-fried, cooked, liver, variety meats and by-products                       72.50
Name: vitamin_b12_mcg, dtype: float64

2

In [ ]:
# foods in the dataset that contain, or are based on eggplant
nutrition.filter(axis=0, regex='(?i)eggplant')

,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,niacin_mg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
name,,,,,,,,,,,,,,,,,,,,,
"Eggplant, raw",100.0,25.0,0.2,NaN,0.0,2.0,6.9,22.0,0.0,0.649,...,0.18,0.034,0.016,0.076,0.0,0.0,0.66,0.0,0.0,92.30
"Eggplant, pickled",100.0,49.0,0.7,0.1,0.0,1674.0,11.9,20.0,0.0,0.660,...,0.70,0.140,0.063,0.294,0.0,0.0,1.73,0.0,0.0,86.90
"Eggplant, with salt, drained, boiled, cooked",100.0,33.0,0.2,NaN,0.0,239.0,9.4,14.0,0.0,0.600,...,0.23,0.044,0.020,0.093,0.0,0.0,1.13,0.0,0.0,89.67
"Eggplant, without salt, drained, boiled, cooked",100.0,35.0,0.2,NaN,0.0,1.0,9.4,14.0,0.0,0.600,...,0.23,0.044,0.020,0.093,0.0,0.0,0.54,0.0,0.0,89.67

In [ ]:
# foods in the dataset that contain, or are based on eggplant--> Food with maximum sodium
# nutrition.filter(axis=0, regex='(?i)eggplant').sodium_mg.idxmax()
nutrition.filter(axis=0, regex='(?i)eggplant').sodium_mg.nlargest(1)

name
Eggplant, pickled    1674.0
Name: sodium_mg, dtype: float64

3

In [ ]:
# slice of the dataframe that contains 4 random rows and 2 random columns.
nutrition.sample(n=4).sample(n=2, axis=1)

,tryptophan_g,vitamin_a_rae_mcg
name,,
"Fish, with skin (Alaska Native), cooked, halibut",0.335,48.0
"Nuts, boiled and steamed, chinese, chestnuts",0.034,7.0
"Chicken, braised, cooked, meat only, boneless, skinless, breast, broiler or fryers",0.404,10.0
"Syrups, maple",0.000,0.0

# Skill Challenge 2
1. Remove all the food items that contain atleast 1 NaN. Do this in a way that modifies the dataframe, i.e. changes stick. How many food items remain after the exclusions?
2. From the remaining records, isolate those that have between 20 and 40 mg of Vitamin C per 100g serving. Of these foods, which one is the least caloric i.e. has the least calories?
3. How many food items in the dataframe has Vitamin C levels of between 2 and 3 standard deviations(inclusive) above the mean?

1

In [ ]:
# Remove all the food items that contain atleast 1 NaN
nutrition.dropna(axis=0, how='any', inplace=True)

In [ ]:
# food items count that remain after the exclusions
nutrition.shape[0]

7199

2

In [ ]:
# isolate those that have between 20 and 40 mg of Vitamin C per 100g serving
nutrition[nutrition.vitamin_c_mg.between(20,40)]

,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,niacin_mg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
name,,,,,,,,,,,,,,,,,,,,,
"Broccoli, raw, chinese",100.0,30.0,0.8,0.1,0.0,7.0,26.5,104.0,0.0,0.459,...,0.76,0.116,0.053,0.347,0.0,0.0,0.83,0.0,0.0,92.55
"Broccoli raab, cooked",100.0,33.0,0.5,0.1,0.0,56.0,33.6,71.0,0.0,2.015,...,0.52,0.057,0.030,0.150,0.0,0.0,1.11,0.0,0.0,91.41
"Horseradish, prepared",100.0,48.0,0.7,0.1,0.0,420.0,6.5,57.0,0.0,0.386,...,0.69,0.090,0.130,0.339,0.0,0.0,1.76,0.0,0.0,85.08
"Spices, white, pepper",100.0,296.0,2.1,0.6,0.0,5.0,0.0,10.0,0.0,0.212,...,2.12,0.626,0.789,0.616,0.0,0.0,1.59,0.0,0.0,11.42
"Dandelion greens, raw",100.0,45.0,0.7,0.2,0.0,76.0,35.3,27.0,0.0,0.806,...,0.70,0.170,0.014,0.306,0.0,0.0,1.80,0.0,0.0,85.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Beverages, fortified, ready to drink, milk and soy based, chocolate drink",100.0,101.0,1.7,0.4,4.0,63.0,1.6,42.0,42.0,1.688,...,1.69,0.422,1.154,0.057,4.0,0.0,0.97,0.0,13.0,75.82
"Cereals ready-to-eat, Peanut Butter, Multi Grain CHEERIOS, GENERAL MILLS",100.0,390.0,6.2,0.9,0.0,447.0,0.0,714.0,0.0,17.890,...,6.19,0.890,2.700,2.290,0.0,0.0,3.09,0.0,0.0,2.00
"Infant formula, with ARA and DHA, ready-to-feed, ADVANCE, NATURAL CARE, SIMILAC, ABBOTT NUTRITION",100.0,78.0,4.2,2.5,2.0,34.0,6.0,29.0,29.0,3.902,...,4.24,2.544,0.402,0.842,2.0,0.0,0.75,0.0,0.0,85.07
"Cereals ready-to-eat, KELLOGG'S SMART START Strong Heart Antioxidants Cereal, KELLOGG",100.0,371.0,1.5,0.3,0.0,398.0,14.9,800.0,781.0,40.000,...,1.50,0.300,0.100,0.500,0.0,0.0,1.70,0.0,0.0,2.50
"Infant formula, with ARA and DHA, ready-to-feed, with iron, ADVANCE 24, SPECIAL CARE, SIMILAC, ABBOTT NUTRITION",100.0,71.0,3.3,2.1,2.0,34.0,7.0,29.0,29.0,3.927,...,3.26,2.120,0.324,0.737,2.0,0.0,0.60,0.0,0.0,85.61

In [ ]:
# Of these foods, which one is the least caloric
nutrition[nutrition.vitamin_c_mg.between(20,40)].vitamin_c_mg.nsmallest(1)

name
Cereals ready-to-eat, ALPHA-BITS, POST    20.0
Name: vitamin_c_mg, dtype: float64

3

In [ ]:
# How many food items in the dataframe has Vitamin C levels of between 2 and 3 standard deviations(inclusive) above the mean
m = nutrition.vitamin_c_mg.mean()
mp2sd = m + nutrition.vitamin_c_mg.std() * 2
mp3sd = m + nutrition.vitamin_c_mg.std() * 3
print(m, mp2sd, mp3sd)

5.553368523406029 97.76213896818041 143.8665241905676

In [ ]:
result_set = nutrition[nutrition.vitamin_c_mg.between(mp2sd, mp3sd)]
result_set.shape

(17, 75)